chateau.wad
cs_bdog.wad
cs_dust.wad
cs_office.wad
cstrike.wad
de_aztec.wad
de_piranesi.wad
decals.wad
gfx/env/doom1bk.tga
gfx/env/doom1dn.tga
gfx/env/doom1ft.tga
gfx/env/doom1lf.tga
gfx/env/doom1rt.tga
gfx/env/doom1up.tga
halflife.wad
liquids.wad
maps/aim_duztec2.bsp
sound/ambience/rain.wav
sound/ambience/waterrun.wav
