cs_assault.wad
de_piranesi.wad
gfx/env/city1bk.tga
gfx/env/city1dn.tga
gfx/env/city1ft.tga
gfx/env/city1lf.tga
gfx/env/city1rt.tga
gfx/env/city1up.tga
halflife.wad
maps/aim_assault_puff.bsp
models/bigtree.mdl
models/pi_outlamp1.mdl
models/pi_tree.mdl
models/pi_tree1.mdl
models/pi_tree2.mdl
models/pi_treeb.mdl
models/player/guerilla/guerilla.mdl
sprites/glow01.spr
