gfx/env/olybk.tga
gfx/env/olydn.tga
gfx/env/olyft.tga
gfx/env/olylf.tga
gfx/env/olyrt.tga
gfx/env/olyup.tga
maps/aim_mainframe.bsp
models/car_van_swat.mdl
models/dnc_truck1.mdl
models/electrical_box-closed.mdl
models/factory_forklift.mdl
models/gh_tree2.mdl
models/plant.mdl
models/plant2.mdl
models/plant222.mdl
models/sink_white1.mdl
sound/ambience/bird14a.wav
sound/ambience/bird2a.wav
sound/ambience/bird9a.wav
sound/ambience/corridor_room_tone_02.wav
sound/ambience/electrical_box.wav
sound/ambience/exterior_06.wav
sound/ambience/flies1.wav
sound/ambience/flies2.wav
sound/ambience/flies3.wav
sound/ambience/flies4.wav
sound/ambience/flies5.wav
sound/ambience/helicopter_flyby_05.wav
sound/ambience/indoor_hum.wav
sound/ambience/light_hum2.wav
sound/ambience/machine_office_01.wav
sound/ambience/machine_office_02.wav
sound/ambience/machine_office_03.wav
sound/ambience/machine_office_04.wav
sound/ambience/machine_office_05.wav
sound/ambience/machine_office_06.wav
sound/ambience/machine_office_07.wav
sound/ambience/machine_office_08.wav
sound/ambience/machine_office_09.wav
sound/ambience/metalscrapeverb03.wav
sound/ambience/office_phone_ring.wav
sound/ambience/office_projector_fan_lp.wav
sound/ambience/pipes1.wav
sound/ambience/plane2.wav
sound/ambience/refrigerator_cycle.wav
sound/ambience/truck_idle_lp_01.wav
sound/ambience/vending_drone.wav
sound/ambience/vent_loop.wav
sound/ambience/water_flow_loop1.wav
