bad.wad
cstrike.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
maps/aim_ak-colt_pool.bsp
ozzy.wad
sprites/glow01.spr
