gfx/env/xzenon_day_bk.tga
gfx/env/xzenon_day_dn.tga
gfx/env/xzenon_day_ft.tga
gfx/env/xzenon_day_lf.tga
gfx/env/xzenon_day_rt.tga
gfx/env/xzenon_day_up.tga
maps/aim_thera_b1.bsp
models/aim_thera/Bush_Flowers.mdl
models/aim_thera/Butterfly.mdl
models/aim_thera/Cat.mdl
models/aim_thera/aim_thera_v1.mdl
models/aim_thera/bird_1upd.mdl
models/aim_thera/flag.mdl
sound/aim_thera/Aaa.wav
sound/aim_thera/Adelante.wav
sound/aim_thera/AhhUhh.wav
sound/aim_thera/AveMaria.wav
sound/aim_thera/Cat.wav
sound/aim_thera/Fan.wav
sound/aim_thera/Kitchen.wav
sound/aim_thera/Kotelnia.wav
sound/aim_thera/Wind.wav
sprites/aim_thera/glow_sun.spr
