cs_teatp.wad
de_chernobyl.wad
de_indust.wad
de_mupa.wad
de_nopt.wad
de_pripyat.wad
de_rechport.wad
de_trash_metall.wad
gfx/env/city_daybk.tga
gfx/env/city_daydn.tga
gfx/env/city_dayft.tga
gfx/env/city_daylf.tga
gfx/env/city_dayrt.tga
gfx/env/city_dayup.tga
maps/aim_kaadi.bsp
paranoia.wad
rrstar.wad
sprites/ikgrass1.spr
sprites/ikgrass3.spr
sprites/ikgrass4.spr
sprites/ikgrass5.spr
