basics.wad
de_esl_autumn.wad
decals.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
halflife.wad
maps/aim_00.bsp
na_aimtrain.wad
