gfx/env/bluebk.tga
gfx/env/bluedn.tga
gfx/env/blueft.tga
gfx/env/bluelf.tga
gfx/env/bluert.tga
gfx/env/blueup.tga
halflife.wad
liquids.wad
maps/as_oilrig.bsp
models/orange.mdl
sound/ambience/drips.wav
sound/ambience/rocket_groan1.wav
sound/ambience/rocket_groan2.wav
sound/ambience/rocket_groan3.wav
sound/ambience/wind2.wav
sound/apache/ap_rotor4.wav
tswad.wad
xeno.wad
