gfx/env/dustbk.tga
gfx/env/dustdn.tga
gfx/env/dustft.tga
gfx/env/dustlf.tga
gfx/env/dustrt.tga
gfx/env/dustup.tga
halflife.wad
maps/cf_monaco.bsp
models/racecity/Sul-DC_Viper-red.mdl
models/racecity/sobol.mdl
