cs_17b_assault.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
maps/cs_17b_assault.bsp
models/cs_17b_assault/3dm_seagull.mdl
models/cs_17b_assault/78rus_toyota.mdl
models/cs_17b_assault/barrels_pallet.mdl
models/cs_17b_assault/bil2.mdl
models/cs_17b_assault/camion01.mdl
models/cs_17b_assault/car_corolla.mdl
models/cs_17b_assault/echafaud.mdl
models/cs_17b_assault/geo_forklift.mdl
models/cs_17b_assault/hostage_s.mdl
models/cs_17b_assault/moby_porsche.mdl
models/cs_17b_assault/oxygen_tanks.mdl
models/cs_17b_assault/pogr.mdl
models/cs_17b_assault/posteluz.mdl
models/cs_17b_assault/tree_1.mdl
models/cs_17b_assault/truck_mack.mdl
