/models/hostage.mdl
cs_747.wad
gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
halflife.wad
liquids.wad
maps/cs_747.bsp
sound/ambience/computalk2.wav
sound/ambience/dog3.wav
sound/ambience/jetflyby1.wav
sound/ambience/mechwhine.wav
sound/ambience/wind2.wav
sound/misc/plane_drone.wav
sprites/flare1.spr
