cs_assault.wad
decals.wad
gfx/env/city1bk.tga
gfx/env/city1dn.tga
gfx/env/city1ft.tga
gfx/env/city1lf.tga
gfx/env/city1rt.tga
gfx/env/city1up.tga
halflife.wad
maps/cs_assault_upc.bsp
models/hostage.mdl
models/scientist.mdl
sprites/glow01.spr
