gfx/env/expobk.tga
gfx/env/expodn.tga
gfx/env/expoft.tga
gfx/env/expolf.tga
gfx/env/export.tga
gfx/env/expoup.tga
maps/cs_assault_2006.bsp
models/3dm_bulb.mdl
models/Envtrash2.mdl
models/caution.mdl
models/dirt.mdl
models/fork.mdl
models/gins_papersmags.mdl
models/hostage.mdl
models/oldorangeford.mdl
models/scientist.mdl
sound/city1.wav
sound/industrial4.wav
sprites/glow01.spr
sprites/grass2.spr
sprites/ikgrass1.spr
sprites/ikgrass2.spr
