cs_assault.wad
decals.wad
gfx.wad
gfx/env/city1bk.tga
gfx/env/city1dn.tga
gfx/env/city1ft.tga
gfx/env/city1lf.tga
gfx/env/city1rt.tga
gfx/env/city1up.tga
halflife.wad
liquids.wad
maps/cs_assault_1337.bsp
models/hostage.mdl
xeno.wad
