decals.wad
gfx/env/badlandsbk.tga
gfx/env/badlandsdn.tga
gfx/env/badlandsft.tga
gfx/env/badlandslf.tga
gfx/env/badlandsrt.tga
gfx/env/badlandsup.tga
halflife.wad
liquids.wad
maps/cs_arabstreets.bsp
models/head.mdl
models/hostage.mdl
sound/ambience/arabmusic.wav
sound/ambience/dog4.wav
sound/ambience/flies.wav
sound/ambience/industrial4.wav
sound/ambience/steamjet1.wav
sprites/flare1.spr
