/models/uplant1.mdl
/models/uplant3.mdl
cs_assault.wad
gfx/env/chaoscitybk.tga
gfx/env/chaoscitydn.tga
gfx/env/chaoscityft.tga
gfx/env/chaoscitylf.tga
gfx/env/chaoscityrt.tga
gfx/env/chaoscityup.tga
halflife.wad
maps/cs_assaultfire.bsp
models/nuke_case.mdl
models/scientist.mdl
sound/ambience/computalk1.wav
sound/ambience/doorbell.wav
sound/ambience/rocket_groan4.wav
sound/ambience/steamburst1.wav
sound/ambience/tankidle2.wav
sound/ambience/wind2.wav
sound/assaultfire/nuke_ticking.wav
sound/scientist/hello2.wav
sprites/fast_wallpuff1.spr
sprites/fire.spr
sprites/glow01.spr
sprites/glow03.spr
