cs_besiege.wad
decals.wad
gfx/env/camobk.tga
gfx/env/camodn.tga
gfx/env/camoft.tga
gfx/env/camolf.tga
gfx/env/camort.tga
gfx/env/camoup.tga
halflife.wad
maps/cs_besiege.bsp
models/bsg_props/CLOTHES_RACK.MDL
models/bsg_props/[hl-lab.ru]bush.mdl
models/bsg_props/bats.mdl
models/bsg_props/bsg_bush2.mdl
models/bsg_props/bsg_pine.mdl
models/bsg_props/bsg_rocks.mdl
models/bsg_props/bsg_tree2.mdl
models/bsg_props/bsg_treesfront.mdl
models/bsg_props/church_pew.mdl
models/bsg_props/dK_table.mdl
models/bsg_props/nh_fountain.mdl
models/bsg_props/plaka_tree2.mdl
models/bsg_props/switch.mdl
models/bsg_props/tree5.mdl
models/bsg_props/wood_barrel2.mdl
models/hostage.mdl
sound/ambience/drips.wav
sound/besiege_sounds/bats.wav
sound/besiege_sounds/bells.wav
sound/besiege_sounds/la_wind.wav
sound/shogun/shogun_water.wav
sound/shogun/shogunwind.wav
sound/volare/vol-fallb.wav
sprites/besiege_sprites/BGO_PINE1.SPR
sprites/besiege_sprites/bsg_paint1.spr
sprites/besiege_sprites/bsg_paint2.spr
sprites/besiege_sprites/bsg_paint3.spr
sprites/besiege_sprites/bsg_paint4.spr
sprites/besiege_sprites/bsg_paint5.spr
sprites/besiege_sprites/bsg_paint6.spr
sprites/besiege_sprites/man_chain.spr
sprites/besiege_sprites/sho_clouds1c.spr
sprites/besiege_sprites/sho_clouds1d.spr
sprites/besiege_sprites/shogun_mist2.spr
sprites/besiege_sprites/watersmoke.spr
sprites/besiege_sprites/wsplash3.spr
sprites/fire3.spr
sprites/glow01.spr
