gfx/env/TrainYardbk.tga
gfx/env/TrainYarddn.tga
gfx/env/TrainYardft.tga
gfx/env/TrainYardlf.tga
gfx/env/TrainYardrt.tga
gfx/env/TrainYardup.tga
maps/cs_blacksunday2.bsp
models/blacksunday2/basketball.mdl
models/blacksunday2/chair_office.mdl
models/blacksunday2/couch1.mdl
models/blacksunday2/fan.mdl
models/blacksunday2/flower_03.mdl
models/blacksunday2/gins_palmfam600_256.mdl
models/blacksunday2/gins_vase_r.mdl
models/blacksunday2/grandjeep.mdl
models/blacksunday2/grass.mdl
models/blacksunday2/palmtree.mdl
models/blacksunday2/plam_04.mdl
models/blacksunday2/plant_potted.mdl
models/blacksunday2/pz_01.mdl
models/blacksunday2/xt_lamp.mdl
