cs_bdog.wad
cs_bier.wad
cs_cbble.wad
cs_office.wad
de_vegas.wad
es_trinity.wad
gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
halflife.wad
itsItaly.wad
jos.wad
liquids.wad
maps/cs_bier.bsp
models/hostage.mdl
models/uplant1.mdl
models/uplant3.mdl
models/winebottle.mdl
sound/ambience/barmusic.wav
sound/ambience/copter.wav
sound/ambience/dog4.wav
sound/ambience/dronemachine2.wav
