decals.wad
gfx/env/dbbk.tga
gfx/env/dbdn.tga
gfx/env/dbft.tga
gfx/env/dblf.tga
gfx/env/dbrt.tga
gfx/env/dbup.tga
halflife.wad
maps/cs_boxoffice2k.bsp
models/3dmsoda.mdl
models/box_gg1.mdl
models/box_gg2.mdl
models/box_gg3.mdl
models/box_gg4.mdl
models/box_phone.mdl
models/box_phoneb.mdl
models/dead_soda.mdl
models/dfountain.mdl
models/pop.mdl
models/popup.mdl
models/uplant1.mdl
sound/ambience/Madman_CS.wav
sound/ambience/box_bgm1.wav
sound/ambience/box_lobby.wav
sound/ambience/box_phoneb.wav
sound/ambience/box_phoned.wav
sound/ambience/box_popc.wav
sound/ambience/box_posfx.wav
sound/ambience/box_squash.wav
sound/ambience/dead_galaga.wav
sound/ambience/dead_ki.wav
sound/ambience/dead_mk1.wav
sound/ambience/dead_mk2.wav
sound/ambience/dead_pac1.wav
sound/ambience/dead_pac2.wav
sound/ambience/deadchop.wav
sound/ambience/truck1.wav
sprites/flare3.spr
sprites/glow01.spr
