cs_747.wad
cs_bdog.wad
gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
halflife.wad
maps/cs_backalley.bsp
models/hostage.mdl
models/scientist.mdl
sound/ambience/alarm1.wav
sound/ambience/car1.wav
sound/ambience/car2.wav
sound/ambience/cat1.wav
sound/ambience/copter.wav
sound/ambience/dog1.wav
sound/ambience/dog2.wav
sound/ambience/dog3.wav
sound/ambience/dog4.wav
sound/ambience/wind2.wav
sound/buttons/latchlocked1.wav
sound/buttons/latchlocked2.wav
sprites/flare1.spr
