algeria.wad
csa.wad
decals.wad
gfx/env/badlandsbk.tga
gfx/env/badlandsdn.tga
gfx/env/badlandsft.tga
gfx/env/badlandslf.tga
gfx/env/badlandsrt.tga
gfx/env/badlandsup.tga
halflife.wad
maps/cs_campagna.bsp
metaltexes1.wad
models/campagna/fan.mdl
models/campagna/njeep.mdl
models/hostage.mdl
pflanzen.wad
rats.wad
sound/campagna/duxe.wav
sound/campagna/gimbird1.wav
sound/campagna/gimbird2.wav
sound/campagna/gimbird3.wav
sound/campagna/gimwaterrun.wav
sprites/redflare1.spr
tfc2.wad
xenon1.wad
xt_furniture.wad
xt_italia.wad
