gfx/env/52h05bk.tga
gfx/env/52h05dn.tga
gfx/env/52h05ft.tga
gfx/env/52h05lf.tga
gfx/env/52h05rt.tga
gfx/env/52h05up.tga
maps/cs_compound.bsp
models/compound/apc.mdl
models/compound/bluetruck.mdl
models/compound/bochka.mdl
models/compound/elec1.mdl
models/compound/gaz.mdl
models/compound/greenwagon.mdl
models/compound/lamp_street05.mdl
models/compound/powertower.mdl
models/compound/redtruck.mdl
models/compound/shelf001.mdl
models/compound/smokestack1_skybox.mdl
models/compound/tank04.mdl
models/compound/trailer002a.mdl
models/compound/van001a.mdl
sound/ambient.steam01
sound/compound/fluorescent.wav
sound/compound/radio.wav
sound/compound/steam.wav
sound/compound/water.wav
sound/compound/wind.wav
