cs_assault.wad
cs_bdog.wad
gfx/env/city1bk.tga
gfx/env/city1dn.tga
gfx/env/city1ft.tga
gfx/env/city1lf.tga
gfx/env/city1rt.tga
gfx/env/city1up.tga
halflife.wad
maps/cs_hopeless.bsp
models/hostage.mdl
