cs_havana.wad
decals.wad
gfx/env/tornskybk.tga
gfx/env/tornskydn.tga
gfx/env/tornskyft.tga
gfx/env/tornskylf.tga
gfx/env/tornskyrt.tga
gfx/env/tornskyup.tga
halflife.wad
maps/cs_inferno_40cal.bsp
models/barney.mdl
models/hostage.mdl
models/pi_tree3.mdl
sound/ambience/cat1.wav
sound/ambience/cow.wav
sound/ambience/crow.wav
sound/ambience/dog1.wav
sound/ambience/drips.wav
sound/ambience/flies.wav
sound/ambience/guit1.wav
sound/ambience/tankidle2.wav
sound/barney/c2a5_ba_letout.wav
sound/buttons/latchlocked1.wav
torntextures.wad
