decals.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
halflife.wad
itsitaly.wad
maps/cs_italy.bsp
models/chick.mdl
models/scientist.mdl
models/winebottle.mdl
sound/ambience/Guit1.WAV
sound/ambience/Opera.wav
sound/misc/killChicken.wav
sound/misc/sheep.wav
sprites/flare1.spr
