gfx/env/krustykrabbk.tga
gfx/env/krustykrabdn.tga
gfx/env/krustykrabft.tga
gfx/env/krustykrablf.tga
gfx/env/krustykrabrt.tga
gfx/env/krustykrabup.tga
maps/cs_krustykrab.bsp
models/krustykrab/kk_barrel.mdl
models/krustykrab/kk_boatmobile.mdl
models/krustykrab/kk_bus.mdl
models/krustykrab/kk_cash.mdl
models/krustykrab/kk_clock.mdl
models/krustykrab/kk_coral01.mdl
models/krustykrab/kk_coral02.mdl
models/krustykrab/kk_gary.mdl
models/krustykrab/kk_krabsburger.mdl
models/krustykrab/kk_lifebuoy.mdl
models/krustykrab/kk_mrkrabs.mdl
models/krustykrab/kk_patrickstar.mdl
models/krustykrab/kk_police.mdl
models/krustykrab/kk_soda.mdl
models/krustykrab/kk_spongebob.mdl
models/krustykrab/kk_squidward.mdl
models/krustykrab/kk_table.mdl
sound/krustykrab/kk_cash.wav
sound/krustykrab/kk_eat.wav
sound/krustykrab/kk_music.wav
sound/krustykrab/kk_sailor.wav
sound/krustykrab/kk_wind1.wav
sprites/glow01.spr
sprites/krustykrab/kk_anten.spr
sprites/krustykrab/kk_bigboard.spr
sprites/krustykrab/kk_bush1.spr
sprites/krustykrab/kk_bush2.spr
sprites/krustykrab/kk_chair.spr
sprites/krustykrab/kk_coral.spr
sprites/krustykrab/kk_inseto.spr
sprites/krustykrab/kk_medusa.spr
