de_piranesi.wad
decals.wad
dod_anzio.wad
dod_forest.wad
dod_glider.wad
gfx/env/citybk.tga
gfx/env/citydn.tga
gfx/env/cityft.tga
gfx/env/citylf.tga
gfx/env/cityrt.tga
gfx/env/cityup.tga
halflife.wad
maps/cs_mansion09_mod_br.bsp
models/cs_mansion09_br/Arvore_1.mdl
models/cs_mansion09_br/Arvore_2.mdl
models/cs_mansion09_br/Arvore_3.mdl
models/cs_mansion09_br/Arvore_4.mdl
models/cs_mansion09_br/Arvore_5.mdl
models/cs_mansion09_br/Cadeira.mdl
models/cs_mansion09_br/Estatua.mdl
models/cs_mansion09_br/Luz.mdl
models/cs_mansion09_br/Mato_1.mdl
models/cs_mansion09_br/Mato_2.mdl
models/cs_mansion09_br/Mato_3.mdl
models/cs_mansion09_br/Mesa_1.mdl
models/cs_mansion09_br/Mesa_2.mdl
models/cs_mansion09_br/Mesa_3.mdl
models/cs_mansion09_br/Relogio_1.mdl
models/cs_mansion09_br/barril.mdl
models/cs_mansion09_br/ventilador.mdl
models/scientist.mdl
sound/cs_mansion09_br/Cachorro.wav
sound/cs_mansion09_br/Natu_1.wav
sound/cs_mansion09_br/copter.wav
sound/cs_mansion09_br/metal-1.wav
sound/cs_mansion09_br/metal-2.wav
sound/cs_mansion09_br/relogio.wav
