1337.wad
de_meco.wad
de_outrage.wad
de_trome.wad
de_vine.wad
decals.wad
gfx/env/desbk.tga
gfx/env/desdn.tga
gfx/env/desft.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desup.tga
halflife.wad
maps/cs_max.bsp
models/hostage.mdl
sound/ambience/bee1.wav
sound/ambience/pounder.wav
sound/ambience/squeeks2.wav
