gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
maps/cs_nmhotel.bsp
models/bathroom_toilet.mdl
models/canopy_withroller.mdl
models/cc_head.mdl
models/coffee_maker.mdl
models/hostage.mdl
models/nm_bush1.mdl
models/nm_bush3.mdl
models/nm_cz_plant6big.mdl
models/palmtree.mdl
models/pi_tree3.mdl
models/plant_potted.mdl
models/table_cafe.mdl
sound/nm_bungle_charity.wav
sound/nm_frampton_theway.wav
sound/nm_moby_rafters.wav
sound/vend.wav
sprites/glow01.spr
