gfx/env/nightsky_bk.tga
gfx/env/nightsky_dn.tga
gfx/env/nightsky_ft.tga
gfx/env/nightsky_lf.tga
gfx/env/nightsky_rt.tga
gfx/env/nightsky_up.tga
maps/cs_truckstop_b1.bsp
models/hostage.mdl
models/player/guerilla/guerilla.mdl
models/truckstop/b4x4.mdl
models/truckstop/bus.mdl
models/truckstop/cactus_medium.mdl
models/truckstop/car1.mdl
models/truckstop/coke_box.mdl
models/truckstop/copcar_v2.mdl
models/truckstop/fan02.mdl
models/truckstop/gmc_norm2.mdl
models/truckstop/hostage01.mdl
models/truckstop/hostage03.mdl
models/truckstop/junkytrl.mdl
models/truckstop/kenworth2.mdl
models/truckstop/kenworth_w_tanker_v3.mdl
models/truckstop/largecar1.mdl
models/truckstop/mack2.mdl
models/truckstop/peterbilt.mdl
models/truckstop/phone.mdl
models/truckstop/plant_potted.mdl
models/truckstop/seif.mdl
models/truckstop/sg_smcouch.mdl
models/truckstop/trailer.mdl
models/truckstop/truck_old_2.mdl
sound/ambience/truck2.wav
sound/ambient/machines/power_transformer_loop_2.wav
sound/cricket.wav
sound/fire.wav
sound/flies.wav
sound/truckstop/acdc_highway_to_hell.wav
sound/truckstop/gimmegimmegimme.wav
sound/truckstop/iloverockandroll.wav
sound/truckstop/little_ride.wav
sound/truckstop/police_chatter.wav
sound/wind_se.wav
sprites/fire2.spr
sprites/glow01.spr
sprites/moths.spr
sprites/smokepuff.spr
