cs_office.wad
cs_valleywarehouse.wad
de_vertigo.wad
gfx/env/avantibk.tga
gfx/env/avantidn.tga
gfx/env/avantift.tga
gfx/env/avantilf.tga
gfx/env/avantirt.tga
gfx/env/avantiup.tga
halflife.wad
itsitaly.wad
maps/cs_valleywhouse.bsp
models/cs_valleywarehouse/bag1.mdl
models/cs_valleywarehouse/bag2.mdl
models/cs_valleywarehouse/bg_truck01.mdl
models/cs_valleywarehouse/big_truck.mdl
models/cs_valleywarehouse/bin.mdl
models/cs_valleywarehouse/buzz_office_calc.mdl
models/cs_valleywarehouse/coffee_maker.mdl
models/cs_valleywarehouse/desert_fern_1.mdl
models/cs_valleywarehouse/desert_grass_1.mdl
models/cs_valleywarehouse/desert_grass_1_big.mdl
models/cs_valleywarehouse/desert_shrub_1.mdl
models/cs_valleywarehouse/ex_truba.mdl
models/cs_valleywarehouse/filecabinet.mdl
models/cs_valleywarehouse/ndf_bjpd.mdl
models/cs_valleywarehouse/ndf_bzls.mdl
models/cs_valleywarehouse/ndf_gusV.mdl
models/cs_valleywarehouse/orvan.mdl
models/cs_valleywarehouse/parl.mdl
models/cs_valleywarehouse/radio.mdl
models/cs_valleywarehouse/rdm_unpaint01.mdl
models/cs_valleywarehouse/re_trashcan.mdl
models/cs_valleywarehouse/res_ev_forklift.mdl
models/cs_valleywarehouse/xen_plant7.mdl
models/cs_valleywarehouse/zp_junk02.mdl
models/hostage.mdl
models/player/terror/terror.mdl
sound/ambience/cricket.wav
sound/ambience/crickets.wav
sound/ambience/truck2.wav
sound/ambience/wind1.wav
sound/cs_valleywarehouse/hornedhowl.wav
sound/cs_valleywarehouse/zorzalcol1.wav
sound/cs_valleywarehouse/zorzalcol2.wav
sound/cs_valleywarehouse/zorzalcol3.wav
sprites/cs_valleywarehouse/bloom309_3.spr
sprites/cs_valleywarehouse/tc_coreglow2.spr
sprites/cs_valleywarehouse/tc_coreglow3.spr
tswad.wad
