de_westwood_hd.wad
gfx/env/westwoodbk.tga
gfx/env/westwooddn.tga
gfx/env/westwoodft.tga
gfx/env/westwoodlf.tga
gfx/env/westwoodrt.tga
gfx/env/westwoodup.tga
maps/css_westwood_hd.bsp
models/de_westwood_hd/barstool.mdl
models/de_westwood_hd/boardbunch.mdl
models/de_westwood_hd/bookcase_small.mdl
models/de_westwood_hd/bush.mdl
models/de_westwood_hd/bush02.mdl
models/de_westwood_hd/chair01.mdl
models/de_westwood_hd/gun_cabinet.mdl
models/de_westwood_hd/kitchen.mdl
models/de_westwood_hd/klos.mdl
models/de_westwood_hd/ladderwood.mdl
models/de_westwood_hd/light_chandelier.mdl
models/de_westwood_hd/piano.mdl
models/de_westwood_hd/pipe.mdl
models/de_westwood_hd/radio_wooden.mdl
models/de_westwood_hd/shelves_wood.mdl
models/de_westwood_hd/table.mdl
models/de_westwood_hd/whabun.mdl
models/de_westwood_hd/wine_barrel.mdl
sound/de_westwood_hd/smallgust2.wav
sound/nm_goodbadugly_hd.wav
