gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
maps/css_westcoast.bsp
models/css_westcoast/com_wheelbarrow.mdl
models/css_westcoast/furniture_couch.mdl
models/css_westcoast/inferno_vespa.mdl
models/css_westcoast/jezus2137.mdl
models/css_westcoast/koparka2.mdl
models/css_westcoast/lamp_floor.mdl
models/css_westcoast/lampa.mdl
models/css_westcoast/mattress_wreck.mdl
models/css_westcoast/rowerekwhetleyek.mdl
models/css_westcoast/wagon.mdl
models/css_westcoast/wood_pile_a.mdl
models/player/guerilla/guerilla.mdl
sound/css_westcoast_sound/birds.wav
sound/css_westcoast_sound/dog5.wav
