gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
maps/css_overpass.bsp
models/pred_plant.mdl
sound/ambience/Birds4.wav
sound/ambience/Birds8.wav
sound/ambience/Birds9.wav
sound/ambience/alarm1.wav
sound/ambience/bee1.wav
sound/ambience/bee2.wav
sound/ambience/boomer.wav
sound/ambience/cicada3.wav
sound/ambience/flies.wav
sound/ambience/industrial2.wav
sound/ambience/lv_jubilee.wav
sound/ambience/lv_neon.wav
sound/ambience/squeeks1.wav
sound/ambience/squeeks2.wav
sprites/flare1.spr
