decals.wad
gfx/env/rubblebk.tga
gfx/env/rubbledn.tga
gfx/env/rubbleft.tga
gfx/env/rubblelf.tga
gfx/env/rubblert.tga
gfx/env/rubbleup.tga
halflife.wad
maps/de_1945_cz.bsp
models/schultz/blackcar.mdl
models/schultz/cromwell.mdl
models/schultz/jagd.mdl
models/schultz/jeep.mdl
models/schultz/pastis.mdl
models/schultz/sandbags_gerade.mdl
models/schultz/streetlight_saints.mdl
models/schultz/tree_japan_round.mdl
models/schultz/truck.mdl
sound/schultz/damage_guns_loop.wav
