ass.wad
decals.wad
gfx/env/diskygordes_bk.tga
gfx/env/diskygordes_dn.tga
gfx/env/diskygordes_ft.tga
gfx/env/diskygordes_lf.tga
gfx/env/diskygordes_rt.tga
gfx/env/diskygordes_up.tga
maps/de_3amok.bsp
models/diman/barrel_metal.mdl
models/diman/barrels_pallet.mdl
models/diman/bush_evergreen.mdl
models/diman/fire_extinguisher.mdl
models/diman/jeep-russian.mdl
models/diman/lamp_street-euro.mdl
models/diman/pallet_stack.mdl
models/diman/trash_02.mdl
models/diman/trashv01.mdl
models/diman/tree_brownv01.mdl
models/diman/truck_russian-large.mdl
sound/diman/corridor_water.wav
sound/diman/ne.wav
sound/diman/ptichki.wav
sound/diman/ptichki2.wav
sound/diman/pticki3.wav
sound/diman/town_ambience.wav
