de_80s.wad
gfx/env/bluebk.tga
gfx/env/bluedn.tga
gfx/env/blueft.tga
gfx/env/bluelf.tga
gfx/env/bluert.tga
gfx/env/blueup.tga
halflife.wad
maps/de_80s.bsp
models/uplant1.mdl
sound/ambience/fallscream.wav
sound/de_80s/song_miami.wav
sound/de_80s/song_petshop.wav
sound/de_80s/song_radiogaga.wav
sound/de_80s/song_sleep.wav
sound/de_80s/song_top1.wav
sound/de_80s/song_walk.wav
sprites/snow.spr
