chateau.wad
cs_bdog.wad
cs_havana.wad
cs_office.wad
de_airstrip.wad
de_piranesi.wad
decals.wad
gfx/env/tornskybk.tga
gfx/env/tornskydn.tga
gfx/env/tornskyft.tga
gfx/env/tornskylf.tga
gfx/env/tornskyrt.tga
gfx/env/tornskyup.tga
halflife.wad
maps/de_airstrip.bsp
models/PG-150.mdl
models/bigtree.mdl
models/bush.mdl
models/palmtree.mdl
models/pred_plant.mdl
sound/ambience/birds3.wav
sound/ambience/birds4.wav
sound/ambience/birds5.wav
sound/ambience/birds8.wav
sound/ambience/birds9.wav
sprites/glow02.spr
sprites/glow03.spr
sprites/ikgrass1.spr
sprites/ikgrass2.spr
sprites/ikgrass3.spr
sprites/ikgrass4.spr
zeditor.wad
