1.wad
aim_ritual2.wad
de_aztec.wad
de_aztec3.wad
de_aztec_16.wad
de_copan.wad
decals.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
maps/de_aztec_1337.bsp
models/abone_template1.mdl
models/pred_plant.mdl
models/skeleton.mdl
ozzy2.wad
sound/ambience/crickets.wav
sound/ambience/thunder_clap.wav
sprites/glow02.spr
