cs_assault.wad
cs_bdog.wad
gfx/env/c2nitebk.tga
gfx/env/c2nitedn.tga
gfx/env/c2niteft.tga
gfx/env/c2nitelf.tga
gfx/env/c2nitert.tga
gfx/env/c2niteup.tga
halflife.wad
maps/de_aztec_urban.bsp
models/fork.mdl
models/industrywest/gins_flatscrn.mdl
models/props/atm.mdl
models/props/aztec_statue.mdl
models/props/car_dealers.mdl
models/props/car_police.mdl
models/props/chair_office.mdl
models/props/lamp_hanging-industrial.mdl
models/props/light_traffic-US.mdl
models/props/machinery_static.mdl
models/props/phone_pay-US.mdl
models/props/pipe_double.mdl
models/props/trash_trashcan.mdl
models/props/tree_tree6.mdl
sound/ambience/aztec_urban/att.wav
sound/ambience/aztec_urban/polizia.wav
sound/ambience/aztec_urban/rain.wav
sound/ambience/aztec_urban/salsadance.wav
sound/ambience/car.wav
sound/ambience/tankidle2.wav
sound/miami/policeradio.wav
sprites/flare1.spr
