de_aztec.wad
decals.wad
gfx/env/doom1bk.tga
gfx/env/doom1dn.tga
gfx/env/doom1ft.tga
gfx/env/doom1lf.tga
gfx/env/doom1rt.tga
gfx/env/doom1up.tga
halflife.wad
maps/de_aztec_mini.bsp
models/abone_template1.mdl
models/pred_plant.mdl
models/skeleton.mdl
sound/ambience/thunder_clap.wav
sprites/glow02.spr
sprites/ikgrass1.spr
sprites/ikgrass2.spr
sprites/ikgrass3.spr
