gfx/env/grnplsntbk.tga
gfx/env/grnplsntdn.tga
gfx/env/grnplsntft.tga
gfx/env/grnplsntlf.tga
gfx/env/grnplsntrt.tga
gfx/env/grnplsntup.tga
halflife.wad
maps/de_amr.bsp
models/camion.mdl
models/forts.mdl
models/palmtreez.mdl
sound/ambience/bee1.wav
sound/ambience/flies.wav
sound/ambience/sandfall1.wav
sound/ambience/techamb2.wav
sound/ambience/wind2.wav
sprites/glow01.spr
sprites/yelflare1.spr
