bigbro.wad
chateau.wad
cs_bdog.wad
cs_havana.wad
cs_office.wad
de_airstrip.wad
de_aztec.wad
de_piranesi.wad
decals.wad
gfx/env/doom1bk.tga
gfx/env/doom1dn.tga
gfx/env/doom1ft.tga
gfx/env/doom1lf.tga
gfx/env/doom1rt.tga
gfx/env/doom1up.tga
halflife.wad
maps/de_aztec.bsp
models/abone_template1.mdl
models/pred_plant.mdl
models/skeleton.mdl
sound/ambience/rain.wav
sound/ambience/thunder_clap.wav
sprites/glow02.spr
sprites/ikgrass1.spr
sprites/ikgrass2.spr
sprites/ikgrass3.spr
tfc2.wad
zeditor.wad
