cs_cbble.wad
de_austria.wad
decals.wad
gfx/env/austriabk.tga
gfx/env/austriadn.tga
gfx/env/austriaft.tga
gfx/env/austrialf.tga
gfx/env/austriart.tga
gfx/env/austriaup.tga
halflife.wad
itsitaly.wad
maps/de_austria.bsp
models/de_austria_models/apfel.mdl
models/de_austria_models/charles.mdl
models/de_austria_models/souther.mdl
models/lv_bottle.mdl
models/winebottle.mdl
sound/ambience/burning1.wav
sound/ambience/cat1.wav
sound/ambience/crow.wav
sound/ambience/dog5.wav
sound/ambience/drips.wav
sound/ambience/waterrun.wav
sound/de_austria_sounds/auto_boom.wav
sound/de_austria_sounds/explode4.wav
sound/de_austria_sounds/hurz_mono_kurz.wav
sound/de_austria_sounds/tree_fall.wav
sound/de_austria_sounds/tree_kkrrrr.wav
sprites/de_austria_sprites/ORION.spr
sprites/de_austria_sprites/Takeshi.spr
sprites/de_austria_sprites/austria_explo1.spr
sprites/de_austria_sprites/austria_explo2.spr
sprites/de_austria_sprites/austria_fire.spr
sprites/de_austria_sprites/austria_glow.spr
sprites/flare1.spr
sprites/wsplash3.spr
