cs_cbble.wad
cs_havana.wad
de_airstrip.wad
decals.wad
gfx/env/sky_day03_06bk.tga
gfx/env/sky_day03_06dn.tga
gfx/env/sky_day03_06ft.tga
gfx/env/sky_day03_06lf.tga
gfx/env/sky_day03_06rt.tga
gfx/env/sky_day03_06up.tga
itsitaly.wad
maps/de_aisle_esl.bsp
models/bigtree.mdl
models/de_aisle/bicycle.mdl
models/de_aisle/bush_fern_small.mdl
models/de_aisle/bush_noleaves.mdl
models/de_aisle/car_lada.mdl
models/de_aisle/rustcar3.mdl
models/de_aisle/slltreet.mdl
models/de_aisle/tree_noleaves.mdl
sound/ambience/cricket.wav
sound/de_aisle/keycat1.wav
sound/plats/vehicle4.wav
sprites/glow01.spr
