[thesurgeon].wad
cs_assault2k.wad
cs_bdog.wad
decals.wad
desnow.wad
gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
halflife.wad
jos.wad
kp_props.wad
maps/de_aldi2k.bsp
mp_tile.wad
nolf_objects.wad
nolf_wood.wad
sound/aldi2k/aldisd.wav
sound/aldi2k/ansage.wav
sound/aldi2k/city01.wav
sound/aldi2k/copter.wav
sprites/glow01.spr
swat3.wad
