gfx/env/sunnybk.tga
gfx/env/sunnydn.tga
gfx/env/sunnyft.tga
gfx/env/sunnylf.tga
gfx/env/sunnyrt.tga
gfx/env/sunnyup.tga
maps/de_aztec_suncsm.bsp
models/de_dust2_magmas/3dm_chair.mdl
models/de_dust2_magmas/arbuste.mdl
models/de_dust2_magmas/bathroom_toilet.mdl
models/de_dust2_magmas/halla_grass1c.mdl
models/de_dust2_magmas/halla_palmtree1.mdl
models/de_dust2_magmas/lettreacalou.mdl
models/de_dust2_magmas/lettrebcalou.mdl
models/de_dust2_magmas/palm1.mdl
models/de_dust2_magmas/pcgprgrass1.mdl
models/de_dust2_magmas/piralodon.mdl
sound/de_dust2_magmas/o_i_mouches.wav
sound/de_dust2_magmas/seagull1.wav
sound/de_dust2_magmas/ventdesert.wav
sprites/de_dust2_magmas/fire.spr
sprites/de_dust2_magmas/megalodon.spr
