de_alps.wad
decals.wad
gfx/env/mad_snow3_bk.tga
gfx/env/mad_snow3_dn.tga
gfx/env/mad_snow3_ft.tga
gfx/env/mad_snow3_lf.tga
gfx/env/mad_snow3_rt.tga
gfx/env/mad_snow3_up.tga
maps/de_alps.bsp
models/de_alps/mad_sgrass1.mdl
models/de_alps/mad_tree1.mdl
models/de_alps/mad_tree2.mdl
models/de_alps/mad_tree3.mdl
models/de_alps/mad_tree4.mdl
sound/de_alps/all_ambience1.wav
sound/de_alps/all_bell.wav
sound/de_alps/all_cat1.wav
sound/de_alps/all_crow1.wav
sound/de_alps/all_crow2.wav
sound/de_alps/lo_cave1.wav
sound/de_alps/lo_cavedrips.wav
sound/de_alps/lo_chimes.wav
sound/de_alps/lo_organ_loop.wav
sound/de_alps/lo_water1.wav
sprites/de_alps/colflare.spr
sprites/de_alps/rauchsprite1.spr
