chateau.wad
cs_assault.wad
cs_bdog.wad
de_aztec.wad
de_piranesi.wad
decals.wad
fonts.wad
gfx/env/2desertbk.tga
gfx/env/2desertdn.tga
gfx/env/2desertft.tga
gfx/env/2desertlf.tga
gfx/env/2desertrt.tga
gfx/env/2desertup.tga
halflife.wad
itsitaly.wad
liquids.wad
maps/de_anarchy.bsp
torntextures.wad
