de_source.wad
decals.wad
gfx/env/desbk.tga
gfx/env/desdn.tga
gfx/env/desft.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desup.tga
halflife.wad
maps/de_alexandra.bsp
models/palmierupulii.mdl
prshu.wad
sound/ambience/crickets1.wav
sound/ambience/dustmusic1.wav
sound/ambience/dustmusic3.wav
sound/ambience/flies.wav
sound/ambience/wind_outdoors_1.wav
windowsscurt.wad
