chateau.wad
de_piranesi.wad
decals.wad
gfx/env/xt_fogbk.tga
gfx/env/xt_fogdn.tga
gfx/env/xt_fogft.tga
gfx/env/xt_foglf.tga
gfx/env/xt_fogrt.tga
gfx/env/xt_fogup.tga
halflife.wad
mad_spain.wad
maps/de_bergheim.bsp
sound/ambience/3dmwood.wav
sound/ambience/Birds9.wav
sound/ambience/mornfall.wav
sprites/glow01.spr
sprites/wsplash3.spr
xt_medieval.wad
xt_motel.wad
