/models/pred_plant.mdl
decals.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
maps/de_blue.bsp
models/de_blue/cactus.mdl
models/de_blue/ginsengavenger_palm240_256.mdl
models/de_blue/ginsengavenger_palmgroup.mdl
models/pred_plant.mdl
sound/ambience/Birds1.wav
sound/ambience/Birds4.wav
sound/ambience/Birds6.wav
sound/ambience/cricket.wav
sound/ambience/lv_neon.wav
sound/ambience/wind2.wav
sound/ambience/wren1.wav
sprites/glow01.spr
