gfx/env/sunnybk.tga
gfx/env/sunnydn.tga
gfx/env/sunnyft.tga
gfx/env/sunnylf.tga
gfx/env/sunnyrt.tga
gfx/env/sunnyup.tga
maps/de_bled.bsp
models/mdlbled/FC_GS2.MDL
models/mdlbled/Xen_vase2.mdl
models/mdlbled/adh_horse.mdl
models/mdlbled/bag_food.mdl
models/mdlbled/camel.mdl
models/mdlbled/gins_vase_g.mdl
models/mdlbled/gins_vase_r.mdl
models/mdlbled/gins_vase_y.mdl
models/mdlbled/kir_sau.mdl
models/mdlbled/krukke1a.mdl
models/mdlbled/myloft_poulet.mdl
models/mdlbled/peri_barrel.mdl
models/mdlbled/pot.mdl
models/mdlbled/poule.mdl
models/mdlbled/tain2_bar1sml.mdl
models/mdlbled/waterpump.mdl
models/mdltemple/barrel.mdl
