cs_assault.wad
cs_office.wad
de_aztec.wad
decals.wad
gfx/env/tsccity_bk.tga
gfx/env/tsccity_dn.tga
gfx/env/tsccity_ft.tga
gfx/env/tsccity_lf.tga
gfx/env/tsccity_rt.tga
gfx/env/tsccity_up.tga
halflife.wad
maps/De_BBGv5.bsp
