gfx/env/letobk.tga
gfx/env/letodn.tga
gfx/env/letoft.tga
gfx/env/letolf.tga
gfx/env/letort.tga
gfx/env/letoup.tga
maps/de_crete_island.bsp
models/leto/biljka.mdl
models/leto/prikolica.mdl
models/pallet_with_bags.mdl
models/palmtree.mdl
sound/ambience/3dmbridge.wav
sound/ambience/bee1.wav
sound/ambience/birds4.wav
sound/ambience/birds9.wav
sound/ambience/cricket.wav
sound/ambience/des_wind3.wav
sound/ambience/rd_shipshorn.wav
sound/ambience/waterrun.wav
sound/de_torn/torn_water2.wav
sprites/glow01.spr
