cs_bdog.wad
cs_thunder.wad
decals.wad
gfx/env/sky2bk.tga
gfx/env/sky2dn.tga
gfx/env/sky2ft.tga
gfx/env/sky2lf.tga
gfx/env/sky2rt.tga
gfx/env/sky2up.tga
halflife.wad
hummer.wad
khark.wad
maps/de_concrete_x.bsp
sound/ambience/city01.wav
sound/ambience/fanrot.wav
sound/ambience/heli1.wav
spinehavana.wad
sprites/glow01.spr
tfc2.wad
