chateau.wad
cs_cbble.wad
cs_havana.wad
de_piranesi.wad
decals.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
maps/de_coastal.bsp
models/pi_tree1.mdl
models/pi_tree2.mdl
models/pi_tree3.mdl
models/player/guerilla/guerilla.mdl
sound/ambience/rd_waves.wav
sound/de_torn/tk_windStreet.wav
sound/de_torn/torn_AK-47.wav
sound/de_torn/torn_MGun1.wav
sound/de_torn/torn_water2.wav
sprites/glow01.spr
torntextures.wad
