as_riverside.wad
de_storm.wad
gfx/env/inletduskbk.tga
gfx/env/inletduskdn.tga
gfx/env/inletduskft.tga
gfx/env/inletdusklf.tga
gfx/env/inletduskrt.tga
gfx/env/inletduskup.tga
itsItaly.wad
mad_spain.wad
mad_spain_addon.wad
maggot1-2.wad
maps/de_callipolia.bsp
paintings.wad
sound/ambience/cricket.wav
sound/ambience/wind2.wav
sprites/flare1.spr
torntextures.wad
