chateau.wad
cs_cbble.wad
de_airstrip.wad
de_storm.wad
de_vertigo.wad
gfx/env/cxbk.tga
gfx/env/cxdn.tga
gfx/env/cxft.tga
gfx/env/cxlf.tga
gfx/env/cxrt.tga
gfx/env/cxup.tga
halflife.wad
maps/de_cache.bsp
models/bush.mdl
models/de_cache/ACUnit02.mdl
models/de_cache/Crate_ExtraLarge.mdl
models/de_cache/Firetrap_PropaneCanister01a.mdl
models/de_cache/Gasmeter003a.mdl
models/de_cache/LargeBush02.mdl
models/de_cache/Light_security.mdl
models/de_cache/PipeSet32d_256_001a.mdl
models/de_cache/Semi_truck.mdl
models/de_cache/Tree_city01.mdl
models/de_cache/car004a.mdl
models/de_cache/concrete_debris256Barricade001a.mdl
models/de_cache/crate_small.mdl
models/de_cache/grass.mdl
models/de_cache/hand_truck.mdl
models/de_cache/refinery_01_skybox.mdl
models/de_cache/train_ladder.mdl
models/de_cache/trees_dryleaves01.mdl
models/de_cache/wood_crate001a.mdl
models/de_cache/wood_crate002a.mdl
models/fern.mdl
torntextures.wad
