arctic.wad
cs_clan1_mill.wad
decals.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
liquids.wad
maps/de_clan1_mill.bsp
models/chick.mdl
models/player/gsg9/gsg9.mdl
models/player/leet/leet.mdl
models/player/urban/urban.mdl
models/player/vip/vip.mdl
shoothouse.wad
sound/ambience/wind2.wav
stadium.wad
tfc2.wad
training.wad
trainingaddon.wad
urbaneuro.wad
xeno.wad
zeditor.wad
