de_contra.wad
decals.wad
fenley_park.wad
gfx/env/desbk.tga
gfx/env/desdn.tga
gfx/env/desft.tga
gfx/env/deslf.tga
gfx/env/desrt.tga
gfx/env/desup.tga
liquids.wad
maps/de_contra.bsp
models/de_contra/grass1a.mdl
models/de_contra/grass1b.mdl
models/de_contra/grass1c.mdl
models/de_contra/plant1.mdl
models/de_contra/plant2.mdl
sj_aztec.wad
sound/de_torn/torn_water2.wav
sprites/glow03.spr
