decals.wad
gfx/env/grnplsntbk.tga
gfx/env/grnplsntdn.tga
gfx/env/grnplsntft.tga
gfx/env/grnplsntlf.tga
gfx/env/grnplsntrt.tga
gfx/env/grnplsntup.tga
halflife.wad
maps/de_crizatii.bsp
models/lag_palm240_256.mdl
sound/ambience/bee1.wav
sound/ambience/bee2.wav
sound/ambience/industrial1.wav
sound/ambience/industrial2.wav
sound/ambience/industrial3.wav
sound/ambience/industrial4.wav
sound/ambience/wind1.wav
sprites/xsmoke3.spr
