czde_canal.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
maps/de_canal_cz.bsp
models/props/airconditioner.mdl
models/props/bush_palmplant.mdl
models/props/electrical_box-closed.mdl
models/props/fire_extinguisher.mdl
models/props/generator.mdl
models/props/lab_oscilliscope.mdl
models/props/lamp_hanging-industrial.mdl
models/props/light_bulb.mdl
models/props/machinery_static.mdl
models/props/tree_palm.mdl
sound/ambience/camp_amb.wav
sound/ambience/camp_flyloop.wav
sound/ambience/canal_amb1.wav
sound/ambience/canal_foghorn.wav
sound/ambience/canal_wtrlap_loop.wav
sprites/glow03.spr
