chateau.wad
cs_assault.wad
cs_bdog.wad
cs_cbble.wad
cs_havana.wad
de_vertigo.wad
decals.wad
gfx/env/mpa89_csbk.tga
gfx/env/mpa89_csdn.tga
gfx/env/mpa89_csft.tga
gfx/env/mpa89_cslf.tga
gfx/env/mpa89_csrt.tga
gfx/env/mpa89_csup.tga
halflife.wad
maps/de_deadbolt.bsp
models/deadbolt/truck.mdl
sound/ambience/voltage.wav
sprites/flare1.spr
torntextures.wad
