gfx/env/badlandsbk.tga
gfx/env/badlandsdn.tga
gfx/env/badlandsft.tga
gfx/env/badlandslf.tga
gfx/env/badlandsrt.tga
gfx/env/badlandsup.tga
halflife.wad
liquids.wad
maps/de_dustier.bsp
sound/ambience/copter.wav
sound/de_dustier/dustier_eagle.wav
sound/de_dustier/dustier_eagle1.wav
sound/de_dustier/dustier_eagle2.wav
sound/de_dustier/rat3.wav
sound/de_dustier/sherman.wav
sound/de_dustier/tankup.wav
sound/de_dustier/water_flowing1.wav
