gfx/env/sunnybk.tga
gfx/env/sunnydn.tga
gfx/env/sunnyft.tga
gfx/env/sunnylf.tga
gfx/env/sunnyrt.tga
gfx/env/sunnyup.tga
maps/de_dust2_suncsm.bsp
models/de_dust2_magmas/3dm_chair.mdl
models/de_dust2_magmas/abritcalou.mdl
models/de_dust2_magmas/arbuste.mdl
models/de_dust2_magmas/fdgr.mdl
models/de_dust2_magmas/halla_palmtree1.mdl
models/de_dust2_magmas/hessi_bank01.mdl
models/de_dust2_magmas/lamp_citylight_small.mdl
models/de_dust2_magmas/lettreacalou.mdl
models/de_dust2_magmas/lettrebcalou.mdl
models/de_dust2_magmas/palm1.mdl
models/de_dust2_magmas/pcgkupol2.mdl
models/de_dust2_magmas/plaka_lilpalm.mdl
models/de_dust2_magmas/well_dahab.mdl
sound/de_dust2_magmas/cigales.wav
sound/de_dust2_magmas/o_i_mouches.wav
sound/de_dust2_magmas/o_i_oiseaux.wav
sound/de_dust2_magmas/seagull1.wav
sound/de_dust2_magmas/sp_cavedrips.wav
sound/de_dust2_magmas/ventdesert.wav
sound/de_dust2_magmas/waterrun.wav
sprites/de_dust2_magmas/megalodon.spr
sprites/de_dust2_magmas/watersmoke.spr
