as_tundra.wad
code21.wad
de_dust2_xmas.wad
decals.wad
gfx/env/arcnbk.tga
gfx/env/arcndn.tga
gfx/env/arcnft.tga
gfx/env/arcnlf.tga
gfx/env/arcnrt.tga
gfx/env/arcnup.tga
halflife.wad
maps/de_dust2_xmas.bsp
models/xmasblock/lekstok.mdl
models/xmasblock/sneeuwman.mdl
models/xmasblock/snow_tree.mdl
models/xmasblock/traineau_2.mdl
nw.wad
sound/xmasblock/coolwind2.wav
