gfx/env/tsccity_bk.tga
gfx/env/tsccity_dn.tga
gfx/env/tsccity_ft.tga
gfx/env/tsccity_lf.tga
gfx/env/tsccity_rt.tga
gfx/env/tsccity_up.tga
maps/de_dizzy_go.bsp
models/go_dizzy/concretebags.mdl
models/go_dizzy/constructioncrane01.mdl
models/go_dizzy/constructioncrane01_top.mdl
models/go_dizzy/dizzy_generator_full.mdl
models/go_dizzy/dizzy_ibeam_bundle.mdl
models/go_dizzy/dizzy_insulation_bundle.mdl
models/go_dizzy/dizzy_metal_sawhorse.mdl
models/go_dizzy/metal_ladder_01.mdl
models/go_dizzy/nuke_roof_cap_03_large.mdl
sound/ambience/fallscream.wav
sound/ambience/wind2.wav
