gfx/env/snowlake_bk.tga
gfx/env/snowlake_dn.tga
gfx/env/snowlake_ft.tga
gfx/env/snowlake_lf.tga
gfx/env/snowlake_rt.tga
gfx/env/snowlake_up.tga
halflife.wad
maps/de_dust2_snow.bsp
sound/ambience/wind.wav
sound/ambience/wind1.wav
