chateau.wad
cs_wolfenstein.wad
czde_sienna.wad
de_nereza.wad
de_piranesi.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
halflife.wad
itsitaly.wad
mad_spain.wad
mad_spain_addon.wad
map_de_inferno.wad
maps/de_damage_village.bsp
models/player/guerilla/guerilla.mdl
sound/ambience/Birds4.wav
sound/ambience/Birds9.wav
sprites/glow01.spr
