basics.wad
cs_cbble.wad
de_esl_autumn.wad
de_piranesi.wad
decals.wad
gfx/env/badlandsbk.tga
gfx/env/badlandsdn.tga
gfx/env/badlandsft.tga
gfx/env/badlandslf.tga
gfx/env/badlandsrt.tga
gfx/env/badlandsup.tga
halflife.wad
maps/de_esl_autumn.bsp
models/eslmap/gim_birke_big.mdl
models/eslmap/gim_birke_small.mdl
models/eslmap/hessi_baum03.mdl
sound/ambience/Birds4.wav
sound/ambience/cat1.wav
sound/ambience/dog2.wav
sound/ambience/drips.wav
sound/ambience/flies.wav
sound/ambience/lv_neon.wav
sound/eslmap/guitar.wav
