basics.wad
cs_havana.wad
de_piranesi.wad
decals.wad
gfx/env/tornskybk.tga
gfx/env/tornskydn.tga
gfx/env/tornskyft.tga
gfx/env/tornskylf.tga
gfx/env/tornskyrt.tga
gfx/env/tornskyup.tga
halflife.wad
itsitaly.wad
maps/de_esl_villaggio_b1.bsp
models/hessi_bank.mdl
models/pi_fern.mdl
models/pi_outlamp1.mdl
models/pi_tree3.mdl
sprites/glow02.spr
torntextures.wad
verano.wad
villaggio.wad
