decals.wad
gfx/env/grnplsntbk.tga
gfx/env/grnplsntdn.tga
gfx/env/grnplsntft.tga
gfx/env/grnplsntlf.tga
gfx/env/grnplsntrt.tga
gfx/env/grnplsntup.tga
halflife.wad
liquids.wad
maps/de_foption.bsp
models/sat_globe.mdl
sound/ambience/computalk2.wav
sound/ambience/des_wind2.wav
sound/ambience/des_wind3.wav
sound/ambience/industrial1.wav
sound/ambience/littlemachine.wav
sound/ambience/rocket_steam1.wav
sound/ambience/rocketrumble1.wav
sound/ambience/steamjet1.wav
sound/ambience/wind2.wav
sound/ambience/wren1.wav
sprites/animglow01.spr
sprites/blueflare1.spr
sprites/flare1.spr
sprites/flare2.spr
sprites/glow01.spr
sprites/stmbal1.spr
sprites/xsmoke1.spr
sprites/xsmoke4.spr
