DQ.wad
cs_bdog.wad
cs_office.wad
decals.wad
gfx/env/DQ_pinewoodbk.tga
gfx/env/DQ_pinewooddn.tga
gfx/env/DQ_pinewoodft.tga
gfx/env/DQ_pinewoodlf.tga
gfx/env/DQ_pinewoodrt.tga
gfx/env/DQ_pinewoodup.tga
halflife.wad
maps/de_floricane.bsp
models/Floricane/DQ_tank.mdl
models/fern.mdl
models/pi_tree1.mdl
models/player/guerilla/guerilla.mdl
sound/ambience/o_i_tuyaux.wav
sound/ambience/water_flowing1.wav
sound/ambience/wind_outdoors_1.wav
sound/events/tutor_msg.wav
sound/floricane/birdambiencedq.wav
sound/floricane/dino.wav
sound/floricane/elevbing.wav
sound/floricane/elevsong.wav
sound/floricane/hawkscream.wav
sprites/floricane/red.spr
sprites/glow01.spr
sprites/ledglow.spr
torntextures.wad
valve/sprites/glow01.spr
valve/sprites/glow02.spr
