gfx/env/dustbk.tga
gfx/env/dustdn.tga
gfx/env/dustft.tga
gfx/env/dustlf.tga
gfx/env/dustrt.tga
gfx/env/dustup.tga
halflife.wad
maps/de_gelu.bsp
models/de_gelu/grsbsh.mdl
models/de_gelu/grsbshs.mdl
models/de_gelu/tr.mdl
