decals.wad
gfx/env/snowlake_bk.tga
gfx/env/snowlake_dn.tga
gfx/env/snowlake_ft.tga
gfx/env/snowlake_lf.tga
gfx/env/snowlake_rt.tga
gfx/env/snowlake_up.tga
halflife.wad
liquids.wad
maps/de_gas26.bsp
models/p_rpg.mdl
sound/ambience/alienwind2.wav
sound/ambience/boomer.wav
sound/ambience/des_wind1.wav
sound/ambience/des_wind3.wav
sound/ambience/drips.wav
sound/ambience/industrial4.wav
sound/ambience/pumper.wav
sound/ambience/steamburst1.wav
sound/ambience/waterfall1.wav
sound/ambience/wind1.wav
sprites/fire.spr
sprites/flare1.spr
sprites/glow01.spr
sprites/mushroom.spr
sprites/snow.spr
sprites/xsmoke1.spr
