de_gash.wad
decals.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
maps/de_gash.bsp
models/de_gash/e4g1e_moskvich2141.mdl
models/de_gash/flag_alb.mdl
models/de_gash/palmtree.mdl
models/de_gash/shade.mdl
models/de_gash/trupi1.mdl
models/de_gash/trupi2.mdl
models/de_gash/trupi3.mdl
models/player/guerilla/guerilla.mdl
