chakawad.wad
de_hitman.wad
de_south.wad
decals.wad
desnow.wad
gfx/env/52h05bk.tga
gfx/env/52h05dn.tga
gfx/env/52h05ft.tga
gfx/env/52h05lf.tga
gfx/env/52h05rt.tga
gfx/env/52h05up.tga
maps/de_goodluck.bsp
models/de_goodluck/bush15.mdl
models/de_goodluck/grass6.mdl
models/de_goodluck/grass7.mdl
models/de_goodluck/jrx_potplant1.mdl
models/de_goodluck/rubbish_cod4_02.mdl
sound/de_goodluck/ambient_summer.wav
sound/de_goodluck/musique.wav
sound/de_goodluck/pa_birdloop.wav
sound/de_goodluck/rnd_dog6.wav
sound/de_goodluck/wind.wav
sound/de_goodluck/wind55.wav
