chateau.wad
cs_havana.wad
de_airstrip.wad
de_piranesi.wad
decals.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
halflife.wad
maps/de_hell2.bsp
models/pi_fern.mdl
models/pi_outlamp1.mdl
sprites/glow01.spr
sprites/grass_01.spr
sprites/grass_03.spr
sprites/ikgrass1.spr
sprites/ikgrass2.spr
sprites/ikgrass3.spr
torntextures.wad
