chateau.wad
cs_damage_esc.wad
de_piranesi.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
halflife.wad
hogwarts1.wad
maps/de_hogwarts.bsp
models/hp/DettanyMesh.mdl
models/hp/bigbook.mdl
models/hp/broom.mdl
models/hp/dresser.mdl
models/hp/fireplacewood.mdl
models/hp/firewood.mdl
models/hp/flipgreenvase.mdl
models/hp/greg.mdl
models/hp/gryfarmoiremesh.mdl
models/hp/gryfbedmesh.mdl
models/hp/gryfchairmesh.mdl
models/hp/gryfcouchmesh.mdl
models/hp/gryftable.mdl
models/hp/gryftrunck2.mdl
models/hp/gryftrunk.mdl
models/hp/hogtrestlebenchmesh.mdl
models/hp/hunchbackwitch.mdl
models/hp/jellyblue.mdl
models/hp/lamppostmesh.mdl
models/hp/potionscauldron.mdl
models/hp/rememberall.mdl
models/hp/singlecandle.mdl
models/hp/skbronzechestMesh.mdl
models/hp/skknightmesh.mdl
models/hp/snitch.mdl
models/hp/telescope.mdl
models/hp/threecandle.mdl
models/hp/transblackboardmesh.mdl
sound/hp/cave_drips1.wav
sound/hp/falldeep2.wav
sound/hp/hagrid.wav
sound/hp/pick_bean.wav
sound/hp/pit.wav
sound/hp/vase_breaking.wav
sprites/glow04.spr
sprites/xffloor.spr
sprites/xsmoke3.spr
