gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
maps/de_hollis.bsp
models/fern.mdl
models/pi_bush.mdl
models/pi_fern.mdl
models/pi_tree.mdl
models/pi_tree1.mdl
models/pi_tree3.mdl
models/player/leet/leet.mdl
models/winebottle.mdl
sound/ambience/Birds7.wav
sound/mistax88/ceilfan1.wav
sound/mistax88/falls2.wav
sound/mistax88/fridgeloop.wav
sound/mistax88/outdoorloop1_wl.wav
sprites/smokepuff.spr
