de_in_30rus_zavod_v2.wad
decals.wad
gfx/env/sp_zavod_bk.tga
gfx/env/sp_zavod_dn.tga
gfx/env/sp_zavod_ft.tga
gfx/env/sp_zavod_lf.tga
gfx/env/sp_zavod_rt.tga
gfx/env/sp_zavod_up.tga
halflife.wad
maps/de_in_30rus_zavod_v2.bsp
models/Explorer/ex_Lada.mdl
models/Explorer/ex_ballon.mdl
models/Explorer/ex_box.mdl
models/Explorer/ex_gazel.mdl
models/Explorer/ex_lada.mdl
models/Explorer/ex_polki.mdl
models/Explorer/ex_stolb.mdl
models/Explorer/ex_truba.mdl
models/Explorer/ex_uaz.mdl
models/Explorer/ex_vagon.mdl
models/explorer/ex_gazel.mdl
models/pi_tree3.mdl
sound/Explorer/ex_ment.wav
sound/Explorer/ex_prodigy.wav
sound/Explorer/ex_radio_ment.wav
sound/Explorer/ex_terror.wav
sound/ambience/3dm_grn_bird.wav
sound/ambience/lv_neon.wav
sound/ambience/rain.wav
sound/ambience/wind1.wav
sprites/dot.spr
