gfx/env/bluebk.tga
gfx/env/bluedn.tga
gfx/env/blueft.tga
gfx/env/bluelf.tga
gfx/env/bluert.tga
gfx/env/blueup.tga
halflife.wad
maps/de_isolation.bsp
sound/de_isolation/iso_bird1.wav
sound/de_isolation/iso_birdloop.wav
sound/de_isolation/iso_cricket.wav
sound/de_isolation/iso_falls.wav
sound/de_isolation/iso_frogs.wav
sound/de_isolation/iso_scream.wav
sound/de_isolation/iso_thunder.wav
sound/radio/meetme.wav
sprites/glow01.spr
sprites/smokepuff.spr
