czde_chateau.wad
czde_inferno.wad
czritual_standard.wad
gfx/env/night2bk.tga
gfx/env/night2dn.tga
gfx/env/night2ft.tga
gfx/env/night2lf.tga
gfx/env/night2rt.tga
gfx/env/night2up.tga
maps/de_inferno_cz.bsp
models/props/books1.mdl
models/props/bush_palmplant.mdl
models/props/bush_planter.mdl
models/props/cafe.mdl
models/props/couch_fabric-wreck.mdl
models/props/fan_ceiling.mdl
models/props/tree_brownv01.mdl
models/props/truck_large-brown.mdl
sprites/yelflare1.spr
