chateau.wad
cs_bdog.wad
cs_cbble.wad
cs_havana.wad
cs_office.wad
de_airstrip.wad
gfx/env/invictusbk.tga
gfx/env/invictusdn.tga
gfx/env/invictusft.tga
gfx/env/invictuslf.tga
gfx/env/invictusrt.tga
gfx/env/invictusup.tga
halflife.wad
maps/de_invictus_v12.bsp
models/de_invictus/apc_arctic.mdl
models/de_invictus/bush_evergreen.mdl
models/de_invictus/bush_fern_small.mdl
models/de_invictus/dumpster_lidclosed_green.mdl
models/de_invictus/fishing_boat.mdl
models/de_invictus/forklift.mdl
models/de_invictus/snowcat.mdl
models/de_invictus/submarine.mdl
models/de_invictus/tdiyeTV.mdl
models/de_invictus/tree_broken.mdl
models/de_invictus/tree_jungle_07.mdl
models/player/guerilla/guerilla.mdl
sound/de_invictus/generator.wav
sound/de_invictus/industrial2.wav
sound/de_invictus/jungle1.wav
sound/de_invictus/jungle2.wav
sound/de_invictus/lv_neon.wav
sound/de_invictus/misc_lightbuzz_loop.wav
sound/de_invictus/motor_loop.wav
sound/de_invictus/pipe_amb3.wav
sound/de_invictus/tdiye.wav
sound/de_invictus/waterrun.wav
sound/de_invictus/wind03.wav
torntextures.wad
