gfx/env/3dm_bikinibk.tga
gfx/env/3dm_bikinidn.tga
gfx/env/3dm_bikinift.tga
gfx/env/3dm_bikinilf.tga
gfx/env/3dm_bikinirt.tga
gfx/env/3dm_bikiniup.tga
maps/de_inferno_suncsm.bsp
models/bar_csm/umbrella_csm.mdl
models/de_dust2_magmas/3dm_beach.mdl
models/de_dust2_magmas/3dm_shark.mdl
models/de_dust2_magmas/cvpt_lampout1.mdl
models/de_dust2_magmas/env_6okcsm.mdl
models/de_dust2_magmas/halla_palmtree1.mdl
models/de_dust2_magmas/halla_shade2a.mdl
models/de_dust2_magmas/halla_shade3.mdl
models/de_dust2_magmas/lettreacalou.mdl
models/de_dust2_magmas/lettrebcalou.mdl
models/de_dust2_magmas/lukturis.mdl
models/de_dust2_magmas/palm1.mdl
models/de_dust2_magmas/pcgprgrass1.mdl
models/de_dust2_magmas/piralodon.mdl
models/de_dust2_magmas/tonneau_csm.mdl
models/de_dust2_magmas/tree_palm.mdl
models/de_dust2_magmas/yatch.mdl
sound/de_d2_magmas/lave.wav
sound/de_dust2_magmas/cigales.wav
sound/de_dust2_magmas/fontaine.wav
sound/de_dust2_magmas/o_i_mouches.wav
sound/de_dust2_magmas/o_i_oiseaux.wav
sound/de_dust2_magmas/seagull1.wav
sound/de_dust2_magmas/ventdesert.wav
sprites/de_dust2_magmas/flames.spr
sprites/de_dust2_magmas/watersmoke.spr
sprites/glow01.spr
