gfx/env/chatbk.tga
gfx/env/chatdn.tga
gfx/env/chatft.tga
gfx/env/chatlf.tga
gfx/env/chatrt.tga
gfx/env/chatup.tga
maps/de_infernold.bsp
models/chatonew/ALIEN_STATUJA.mdl
models/chatonew/PlasticCrate01a.mdl
models/chatonew/ae_pole.mdl
models/chatonew/armure.mdl
models/chatonew/banisterbg1.mdl
models/chatonew/barrel_pallet-pblock.mdl
models/chatonew/barril.mdl
models/chatonew/bench3.mdl
models/chatonew/bord.mdl
models/chatonew/branches.mdl
models/chatonew/bush.mdl
models/chatonew/bush10.mdl
models/chatonew/bush16.mdl
models/chatonew/chatlamp.mdl
models/chatonew/chatocand.mdl
models/chatonew/chatotable.mdl
models/chatonew/chatvigne3.mdl
models/chatonew/dnc_el2.mdl
models/chatonew/dnc_el9.mdl
models/chatonew/dnc_flower03.mdl
models/chatonew/dnc_flower04.mdl
models/chatonew/f3_violin.mdl
models/chatonew/f_feasser.mdl
models/chatonew/flo_grass.mdl
models/chatonew/geo_hennessy.mdl
models/chatonew/jesus.mdl
models/chatonew/mayatnik.mdl
models/chatonew/muellkontainer.mdl
models/chatonew/oldbook2.mdl
models/chatonew/pallet.mdl
models/chatonew/petitarbre2.mdl
models/chatonew/pi_fern.mdl
models/chatonew/pi_tree1.mdl
models/chatonew/plant_potted.mdl
models/chatonew/re_dirt.mdl
models/chatonew/seat1.mdl
models/chatonew/wlight2.mdl
sound/chatonew/bi2_earlybirdies.wav
sound/chatonew/dj_voltage02.wav
sound/chatonew/dusttropfen.wav
sound/chatonew/flies.wav
sound/chatonew/windy.wav
sprites/glow01.spr
sprites/xsmoke3.spr
