cs_havana.wad
de_piranesi.wad
gfx/env/de_joinetskybk.tga
gfx/env/de_joinetskydn.tga
gfx/env/de_joinetskyft.tga
gfx/env/de_joinetskylf.tga
gfx/env/de_joinetskyrt.tga
gfx/env/de_joinetskyup.tga
halflife.wad
itsitaly.wad
maps/de_joinet32.bsp
models/antenna1.mdl
models/cauciuc2.mdl
models/metal_bucket.mdl
models/pallet.mdl
models/pi_shrub.mdl
models/player/guerilla/guerilla.mdl
models/pom1.mdl
models/ramaniwc.mdl
sound/ambience/Birds5.wav
sound/ambience/Birds6.wav
sound/ambience/Birds7.wav
sound/ambience/Birds8.wav
sound/ambience/Birds9.wav
sound/ambience/drips.wav
sound/de_torn/torn_ambience.wav
sound/misc/cow.wav
sound/ramaniflush.wav
sound/sfloop.wav
