gfx/env/dustybk.tga
gfx/env/dustydn.tga
gfx/env/dustyft.tga
gfx/env/dustylf.tga
gfx/env/dustyrt.tga
gfx/env/dustyup.tga
halflife.wad
maps/de_karachi01.bsp
models/golf.mdl
sound/ambience/fire.wav
sound/ambience/kar_belly1b.wav
sound/ambience/kar_bus1c.wav
sound/ambience/kar_street1a.wav
sound/ambience/kar_warz02.wav
sound/ambience/mario2.wav
sound/ambience/muslim.wav
sound/ambience/song01.wav
sound/ambience/waterfall1.wav
sound/weapons/c4_explode1.wav
sprites/fire.spr
sprites/xsmoke1.spr
