gfx/env/losttemplebk.tga
gfx/env/losttempledn.tga
gfx/env/losttempleft.tga
gfx/env/losttemplelf.tga
gfx/env/losttemplert.tga
gfx/env/losttempleup.tga
maps/de_losttemple.bsp
models/de_losttemple/bag_food2.mdl
models/de_losttemple/lamp_portable_standup.mdl
models/de_losttemple/palmier_croche.mdl
models/de_losttemple/palmier_mini.mdl
models/de_losttemple/palmier_normal.mdl
models/de_losttemple/weldtank2.mdl
models/props/bush_fern_small.mdl
models/props/rock_japan_rocks2.mdl
sound/ambience/3dmeagle.wav
sound/ambience/crow.wav
sound/de_losttemple/lt_bird1.wav
sound/de_losttemple/lt_bird2.wav
sound/de_losttemple/lt_bird3.wav
sound/de_losttemple/lt_bird4.wav
sound/de_losttemple/lt_bird5.wav
sound/de_losttemple/lt_tunnel.wav
sound/de_losttemple/lt_wind.wav
sprites/glow01.spr
