gfx/env/arizonabk.tga
gfx/env/arizonadn.tga
gfx/env/arizonaft.tga
gfx/env/arizonalf.tga
gfx/env/arizonart.tga
gfx/env/arizonaup.tga
maps/de_littlehouse_b4.bsp
models/littlehouse/chair.mdl
models/littlehouse/cloche.mdl
models/littlehouse/flo_hanger02.mdl
models/littlehouse/herbe.mdl
models/littlehouse/herbe2.mdl
models/littlehouse/sandbags_gerade.mdl
models/littlehouse/table_dining-mahg.mdl
models/littlehouse/tree1.mdl
models/littlehouse/tree2.mdl
models/littlehouse/tree5.mdl
sound/littlehouse/dingcloche.wav
sound/littlehouse/littlehousedebut.wav
sound/littlehouse/soulage.wav
sound/littlehouse/soundfire.wav
sprites/glow01.spr
sprites/littlehouse/fire.spr
