awp_greesia.wad
de_dust0.wad
de_retuscan.wad
gfx/env/infernobk.tga
gfx/env/infernodn.tga
gfx/env/infernoft.tga
gfx/env/infernolf.tga
gfx/env/infernort.tga
gfx/env/infernoup.tga
halflife.wad
hidden.wad
hs_desertstorm.wad
maps/de_lostparadise.bsp
models/de_paradise/barrel.mdl
models/de_paradise/grass.mdl
models/de_paradise/lamp.mdl
models/de_paradise/lamp2.mdl
models/de_paradise/trash.mdl
models/de_paradise/tree.mdl
sound/ambience/3dmstart.wav
sound/ambience/chimes.wav
sound/ambience/cricket.wav
sound/ambience/dog2.wav
sound/ambience/flies.wav
sound/ambience/rain.wav
sound/ambience/siren.wav
sound/ambience/squitch.wav
sound/ambience/thunder_clap.wav
sprites/glow01.spr
