chateau.wad
cs_assault.wad
cs_cbble.wad
cs_office.wad
de_aztec.wad
de_storm.wad
decals.wad
gfx/env/morningdewbk.tga
gfx/env/morningdewdn.tga
gfx/env/morningdewft.tga
gfx/env/morningdewlf.tga
gfx/env/morningdewrt.tga
gfx/env/morningdewup.tga
halflife.wad
itsitaly.wad
liquids.wad
maps/de_mini_city_s.bsp
models/S3B/forge_tree1.mdl
sound/S3B/de_town_s.wav
sound/ambience/wind2.wav
