/models/de_monastery/bnch.mdl
/models/de_monastery/brlls.mdl
/models/de_monastery/cw.mdl
/models/de_monastery/frplc.mdl
/models/de_monastery/hy.mdl
/models/de_monastery/lntrn2.mdl
/models/de_monastery/mt.mdl
/models/de_monastery/snwstt.mdl
/models/de_monastery/snwtrlrg.mdl
/models/de_monastery/snwtrsmll.mdl
de_monastery.wad
decals.wad
default.wad
gfx/env/monasterybk.tga
gfx/env/monasterydn.tga
gfx/env/monasteryft.tga
gfx/env/monasterylf.tga
gfx/env/monasteryrt.tga
gfx/env/monasteryup.tga
maps/de_monastery.bsp
sound/de_monastery/cw.wav
sound/de_monastery/wnd.wav
