de_mon.wad
gfx/env/mon_sky_bk.tga
gfx/env/mon_sky_dn.tga
gfx/env/mon_sky_ft.tga
gfx/env/mon_sky_lf.tga
gfx/env/mon_sky_rt.tga
gfx/env/mon_sky_up.tga
liquids.wad
maps/de_mon.bsp
models/doenerking/Xen_barrel3_1.mdl
models/doenerking/Xen_barrel4_2.mdl
models/doenerking/Xen_bush_big.mdl
models/doenerking/Xen_tree4.mdl
models/doenerking/Xen_tree4_3.mdl
models/doenerking/Xen_tree6.mdl
models/doenerking/Xen_tree6_3.mdl
models/doenerking/e4g1e_bobby.mdl
models/doenerking/e4g1e_merc.mdl
models/doenerking/e4g1e_moskvich2141.mdl
models/mon_estrutura.mdl
models/mon_fakew.mdl
models/mon_farol.mdl
models/mon_ponte.mdl
models/mon_veg1.mdl
models/mon_veg2.mdl
models/mon_veg3.mdl
sound/ambience/burning1.wav
sound/ambience/chimes.wav
sound/ambience/cicada3.wav
sound/ambience/crow.wav
sound/ambience/des_wind3.wav
sound/ambience/drips.wav
sound/ambience/goal_1.wav
sound/ambience/lv_neon.wav
sound/ambience/port_suckin1.wav
sound/ambience/rd_shipshorn.wav
sound/ambience/rd_waves.wav
sound/ambience/tankidle2.wav
sound/ambience/truck2.wav
sound/ambience/waterrun.wav
sound/ambience/wind2.wav
sound/de_torn/torn_ambience.wav
sound/de_torn/torn_thndrstrike.wav
sound/flmgrexp.wav
sprites/atm_effect.spr
sprites/eexplo.spr
sprites/fexplo.spr
sprites/fire.spr
sprites/glow02.spr
sprites/sp_agua.spr
sprites/sp_agua_h.spr
sprites/xsmoke1.spr
