cs_office.wad
de_aztec.wad
de_piranesi.wad
gfx/env/doom1bk.tga
gfx/env/doom1dn.tga
gfx/env/doom1ft.tga
gfx/env/doom1lf.tga
gfx/env/doom1rt.tga
gfx/env/doom1up.tga
halflife.wad
maps/de_mexica.bsp
models/pred_plant.mdl
sound/ambience/rain.wav
sound/ambience/thunder_clap.wav
sprites/ikgrass1.spr
sprites/ikgrass3.spr
