gfx/env/grassbk.tga
gfx/env/grassdn.tga
gfx/env/grassft.tga
gfx/env/grasslf.tga
gfx/env/grassrt.tga
gfx/env/grassup.tga
halflife.wad
liquids.wad
maps/de_mario_air.bsp
sound/mario2/billblow.wav
sound/mario2/bowser.wav
sound/mario2/cannon.wav
sound/mario2/coin.wav
sound/mario2/falling1.wav
sound/mario2/mess.wav
sound/mario2/pipewarp.wav
sound/mario2/taunt.wav
sound/mario2/thanks.wav
sprites/cloud.spr
sprites/explode1.spr
sprites/spinning_coin.spr
