decals.wad
gfx/env/mhbk.tga
gfx/env/mhdn.tga
gfx/env/mhft.tga
gfx/env/mhlf.tga
gfx/env/mhrt.tga
gfx/env/mhup.tga
halflife.wad
maps/de_mountainhamlet.bsp
models/bookgibs.mdl
models/can.mdl
models/mountainhamlet/ak5scope.mdl
models/mountainhamlet/bell.mdl
models/mountainhamlet/chamagne.mdl
models/mountainhamlet/chick.mdl
models/mountainhamlet/grrenbott.mdl
models/mountainhamlet/gunrack1.mdl
models/mountainhamlet/ksp.mdl
models/mountainhamlet/lamp_glass.mdl
models/mountainhamlet/palma.mdl
models/uplant1.mdl
models/w_chainammo.mdl
sound/ambience/drips.wav
sound/ambience/mountainhamlet/belltoll_mw.wav
sound/ambience/mountainhamlet/birds.wav
sound/ambience/mountainhamlet/bubble_mw.wav
sound/ambience/mountainhamlet/chickamb.wav
sound/ambience/mountainhamlet/chinamusic.wav
sound/ambience/mountainhamlet/chkn_alrmd.wav
sound/ambience/mountainhamlet/erriewind_mw.wav
sound/ambience/mountainhamlet/falls_mw.wav
sound/ambience/mountainhamlet/flush.wav
sound/ambience/mountainhamlet/greg_mw.wav
sound/ambience/mountainhamlet/killChicken.wav
sound/ambience/mountainhamlet/lv_fruit1.wav
sound/ambience/mountainhamlet/scream.wav
sound/ambience/mountainhamlet/toad.wav
sound/ambience/mountainhamlet/towerbell.wav
sound/ambience/mountainhamlet/waterrun_mw.wav
sound/ambience/mountainhamlet/woodcreak.wav
sound/ambience/quail1.wav
sound/buttons/spark3.wav
sound/debris/bustmetal2.wav
sprites/fire.spr
sprites/glow01.spr
sprites/glow04.spr
sprites/xsmoke1.spr
sprites/xsmoke3.spr
sprites/xssmke1.spr
