am6_spay.wad
de_snow_btm.wad
de_snowjob.wad
decals.wad
fy_v126yxatb.wad
gfx/env/backalleybk.tga
gfx/env/backalleydn.tga
gfx/env/backalleyft.tga
gfx/env/backalleylf.tga
gfx/env/backalleyrt.tga
gfx/env/backalleyup.tga
gta3_another.wad
gta3_brooklyn.wad
gta3_chinatown.wad
gta3_jersey.wad
gta3_manhattan.wad
gta3_miscy.wad
gta3_portland.wad
halflife.wad
maps/de_NewYork.bsp
maxpayne.wad
models/De_New_York/Fonapb.mdl
models/De_New_York/NEWyeartree1.mdl
models/De_New_York/briefcase_money.mdl
models/De_New_York/bulb2.mdl
models/De_New_York/car_police03.mdl
models/De_New_York/fan1.mdl
models/De_New_York/fire_hydrant.mdl
models/De_New_York/golf.mdl
models/De_New_York/paris_bar.mdl
models/De_New_York/phone_pay-US.mdl
models/De_New_York/present1.mdl
models/De_New_York/re_deadguy_2.mdl
models/De_New_York/re_dirt.mdl
models/De_New_York/rubble02.mdl
models/De_New_York/swat_van_nypd.mdl
models/De_New_York/taxi.mdl
models/De_New_York/tree.mdl
models/De_New_York/van1_1.mdl
sound/Spay/electro01.wav
sound/ambience/FireMax.wav
sound/de_NewYork/a1_citytraffic.wav
sound/de_NewYork/city01.wav
sound/de_NewYork/jinglebells.wav
sound/de_NewYork/wind_ambience8.wav
spay_edition_1.wad
sprites/flame.spr
sprites/glow01.spr
xelious.wad
