gfx/env/desertbk.tga
gfx/env/desertdn.tga
gfx/env/desertft.tga
gfx/env/desertlf.tga
gfx/env/desertrt.tga
gfx/env/desertup.tga
halflife.wad
maps/de_nuke32.bsp
sound/ambience/cricket.wav
sprites/flare1.spr
