a_bricks.wad
a_roofs.wad
a_woods.wad
czde_inferno.wad
de_chernobyl.wad
de_forge.wad
de_gothicmanor.wad
de_inf.wad
de_odessamama.wad
decals.wad
dm_oc.wad
gfx/env/sp_zavod_bk.tga
gfx/env/sp_zavod_dn.tga
gfx/env/sp_zavod_ft.tga
gfx/env/sp_zavod_lf.tga
gfx/env/sp_zavod_rt.tga
gfx/env/sp_zavod_up.tga
halflife.wad
maps/de_oC2.bsp
oc2.wad
orange.wad
rrstar.wad
spay_edition_1.wad
