decals.wad
gfx/env/sunrisebk.tga
gfx/env/sunrisedn.tga
gfx/env/sunriseft.tga
gfx/env/sunriself.tga
gfx/env/sunrisert.tga
gfx/env/sunriseup.tga
halflife.wad
itsitaly.wad
maps/de_pasta.bsp
models/winebottle.mdl
pasta1.wad
sound/ambience/Fortran_Aquarium_Loop.wav
sound/ambience/Fortran_Italian_4_edit.wav
sound/ambience/Fortran_Italian_5.wav
sound/ambience/Fortran_suburbs_Loop.wav
sound/ambience/burning3.wav
sound/ambience/rocket_groan2.wav
sound/ambience/rocket_groan3.wav
sprites/fire.spr
