de_piranesi.wad
decals.wad
gfx/env/cxbk.tga
gfx/env/cxdn.tga
gfx/env/cxft.tga
gfx/env/cxlf.tga
gfx/env/cxrt.tga
gfx/env/cxup.tga
halflife.wad
maps/de_piranesi.bsp
models/pi_fern.mdl
models/pi_outlamp1.mdl
models/pi_shrub.mdl
models/pi_stlamp.mdl
models/pi_tree.mdl
models/pi_treeb.mdl
sound/ambience/3dmeagle.wav
sound/ambience/Birds4.wav
sound/ambience/Birds6.wav
sound/ambience/Birds9.wav
sound/ambience/car1.wav
sound/ambience/car2.wav
sound/ambience/cow.wav
sound/ambience/crow.wav
sound/ambience/dog1.wav
sound/ambience/dog2.wav
sound/ambience/dog3.wav
sound/ambience/dog4.wav
sound/ambience/dog5.wav
sound/ambience/sheep.wav
sound/ambience/sparrow.wav
sound/ambience/tankidle2.wav
sound/ambience/waterrun.wav
sprites/glow01.spr
