de_plaka.wad
decals.wad
gfx/env/plakabk.tga
gfx/env/plakadn.tga
gfx/env/plakaft.tga
gfx/env/plakalf.tga
gfx/env/plakart.tga
gfx/env/plakaup.tga
maps/de_plaka.bsp
models/de_plaka/plaka_barrel.mdl
models/de_plaka/plaka_barrel2.mdl
models/de_plaka/plaka_bench.mdl
models/de_plaka/plaka_boat1.mdl
models/de_plaka/plaka_car1.mdl
models/de_plaka/plaka_car2.mdl
models/de_plaka/plaka_car4.mdl
models/de_plaka/plaka_chair.mdl
models/de_plaka/plaka_cloth1.mdl
models/de_plaka/plaka_clothes1.mdl
models/de_plaka/plaka_fernofdoom.mdl
models/de_plaka/plaka_furniture1.mdl
models/de_plaka/plaka_glass1.mdl
models/de_plaka/plaka_ladder.mdl
models/de_plaka/plaka_lilpalm.mdl
models/de_plaka/plaka_pillar.mdl
models/de_plaka/plaka_seagull.mdl
models/de_plaka/plaka_seagull2.mdl
models/de_plaka/plaka_shark.mdl
models/de_plaka/plaka_shrubberyyy.mdl
models/de_plaka/plaka_tree1.mdl
models/de_plaka/plaka_tree2.mdl
models/de_plaka/plaka_umbrella.mdl
models/de_plaka/plaka_water.mdl
sound/de_plaka/birds.wav
sound/de_plaka/bouzouki.wav
sound/de_plaka/seagulls.wav
sound/de_plaka/waves.wav
