chateau.wad
cs_cbble.wad
cs_havana.wad
cs_office.wad
de_airstrip.wad
de_piranesi.wad
de_storm.wad
de_vertigo.wad
gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
itsitaly.wad
maps/de_potos.bsp
models/de_potos/AA_PaintPrefab_01_TCH_SMesh.mdl
models/de_potos/Wheebarrow01a.mdl
models/de_potos/flower_barrel.mdl
models/de_potos/gravestone_statue001a.mdl
models/de_potos/pallet_with_bags.mdl
models/de_potos/patio_table2.mdl
models/de_potos/pole_COD4_04.mdl
models/de_potos/s_tree2.mdl
models/de_potos/tree21.mdl
models/de_potos/zps_ficus.mdl
models/de_potos/zps_parkbench.mdl
models/player/guerilla/guerilla.mdl
sound/ambience/Birds6.wav
sound/ambience/dog5.wav
sound/ambience/lv_neon.wav
torntextures.wad
