gfx/env/volarebk.tga
gfx/env/volaredn.tga
gfx/env/volareft.tga
gfx/env/volarelf.tga
gfx/env/volarert.tga
gfx/env/volareup.tga
maps/de_rampz.bsp
models/rampz/arc_fern.mdl
models/rampz/doofbird.mdl
models/rampz/gins_leafy.mdl
models/rampz/pi_bush.mdl
models/rampz/pi_shrub.mdl
models/rampz/shrub_jungle.mdl
models/rampz/swampstuff.mdl
models/rampz/wood_barrel1.mdl
models/rampz/xen_bush_big.mdl
models/rampz/xen_bush_small.mdl
sound/rampz/birdies.wav
sound/rampz/birds4.wav
sound/rampz/birdsenv2.wav
sound/rampz/mornfall.wav
sprites/rampz/rex_leaves1.spr
sprites/rampz/rex_trunk.spr
sprites/rampz/tree1.spr
sprites/rampz/tree2.spr
