gfx/env/skiptonbk.tga
gfx/env/skiptondn.tga
gfx/env/skiptonft.tga
gfx/env/skiptonlf.tga
gfx/env/skiptonrt.tga
gfx/env/skiptonup.tga
maps/de_skipton.bsp
sound/ambience/3dmeagle.wav
sound/ambience/Birds9.wav
sound/ambience/crow.wav
sound/ambience/fallscream.wav
sound/ambience/sparrow.wav
sound/ambience/waterrun.wav
sound/skipton/skipton_greensleaves.wav
sound/skipton/skipton_greensleaves2.wav
sound/skipton/skipton_vento.wav
sound/skipton/skipton_wethree.wav
sound/skipton/skipton_wexford.wav
sprites/skipton/flame.spr
sprites/skipton/rk_yellowflare.spr
sprites/skipton/ski_cloud.spr
