de_santorini.wad
decals.wad
gfx/env/san_bk.tga
gfx/env/san_dn.tga
gfx/env/san_ft.tga
gfx/env/san_lf.tga
gfx/env/san_rt.tga
gfx/env/san_up.tga
grid_cso.wad
maps/de_santorini.bsp
models/bg_light05.mdl
models/de_santorini/bg_houseup01.mdl
models/de_santorini/bg_houseup02.mdl
models/de_santorini/bg_houseup03.mdl
models/longchair01.mdl
models/pi_shrub.mdl
models/pi_tree3.mdl
models/pi_twig.mdl
models/props/lamp_hanging-industrial.mdl
models/shelter/grass_set.mdl
models/whabun01.mdl
models/whabun02.mdl
models/ze_venice/bg_chair.mdl
models/ze_venice/bg_jong.mdl
models/ze_venice/bg_table_set.mdl
models/ze_venice/seagull.mdl
sound/ambience/bell_noloop.wav
sound/ambience/seashore.wav
sprites/glow03.spr
