256.wad
arab.wad
artasai.wad
d2source.wad
gfx/env/saidesbk.tga
gfx/env/saidesdn.tga
gfx/env/saidesft.tga
gfx/env/saideslf.tga
gfx/env/saidesrt.tga
gfx/env/saidesup.tga
liquids.wad
maps/de_sultan.bsp
models/tree1.mdl
sound/ambience/bongo.wav
sound/ambience/crickets1.wav
sound/ambience/dustmusic1.wav
sound/ambience/dustmusic2.wav
sound/ambience/dustmusic3.wav
sound/ambience/lake_water.wav
sound/ambience/wind_outdoors_1.wav
