blazurban.wad
cr.wad
cs_bdog.wad
decals.wad
gfx/env/seabk.tga
gfx/env/seadn.tga
gfx/env/seaft.tga
gfx/env/sealf.tga
gfx/env/seart.tga
gfx/env/seaup.tga
halflife.wad
joesmoe_cm.wad
maps/de_suntower.bsp
megamikedeus2.wad
pheerblaz.wad
qemilitia.wad
smoe_cm2.wad
sound/ambience/rd_waves.wav
sound/ambience/wind2.wav
sprites/flare1.spr
t1ktewers.wad
tewers.wad
tfc2.wad
vb.wad
