cs_assault.wad
cs_havana.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
maps/de_stacja.bsp
sound/de_stacja/odjazd.wav
torntextures.wad
