gfx/env/houseyardbk.tga
gfx/env/houseyarddn.tga
gfx/env/houseyardft.tga
gfx/env/houseyardlf.tga
gfx/env/houseyardrt.tga
gfx/env/houseyardup.tga
maps/de_safehouse_csgo.bsp
models/costabrava/gins_leafy.mdl
models/de_tides/patio_chair.mdl
models/safehouse/antenna_b.mdl
models/safehouse/berz.mdl
models/safehouse/clock01.mdl
models/safehouse/clothes.mdl
models/safehouse/couch_fabric-wreck.mdl
models/safehouse/fence03edit.mdl
models/safehouse/hessi_baum_edited.mdl
models/safehouse/hessi_big_baum.mdl
models/safehouse/lightfixture03_off.mdl
models/safehouse/rakovina.mdl
models/safehouse/rdm_unbots01.mdl
models/safehouse/scar_pillow.mdl
models/safehouse/scar_toiletbwl.mdl
models/safehouse/towel_shhc_001.mdl
models/safehouse/trashcan.mdl
models/safehouse/tree01_small.mdl
models/safehouse/urban_pot.mdl
sound/ambient/machines/truck_idle_lp_01.wav
sound/ambient/wind/birdambiencedq.wav
sound/ambient/wind/tree_sway_wind_lp_02.wav
sound/ambient/wind/tree_sway_wind_lp_03.wav
sound/doors/wood_open.wav
sprites/2dprops/curtains_bright.spr
sprites/2dprops/lamp_spr.spr
sprites/2dprops/lamp_sprite2.spr
sprites/2dprops/uvine02.spr
sprites/buzz/buzz_kt_trava2.spr
sprites/buzz/buzz_kt_trava3.spr
sprites/de_house/buz_pic.spr
sprites/de_house/fc_f_pic_3.spr
sprites/de_house/hessi_tree_edit.spr
sprites/de_house/mirror001.spr
sprites/de_house/offpd.spr
sprites/de_house/offpe.spr
sprites/de_house/offpf.spr
sprites/de_house/offpg.spr
sprites/man_sprites/man_carp4.spr
sprites/xsmoke1.spr
