cs_bdog.wad
gfx/env/ghettobk.tga
gfx/env/ghettodn.tga
gfx/env/ghettoft.tga
gfx/env/ghettolf.tga
gfx/env/ghettort.tga
gfx/env/ghettoup.tga
halflife.wad
itsitaly.wad
maps/de_springer.bsp
sound/ambience/Birds4.wav
sound/ambience/Birds9.wav
sound/ambience/alarm1.wav
sound/ambience/burning3.wav
sound/ambience/car1.wav
sound/ambience/car2.wav
sound/ambience/cat1.wav
sound/ambience/copter.wav
sound/ambience/dog1.wav
sound/ambience/dog4.wav
sound/ambience/dog5.wav
sound/ambience/dog6.wav
sound/ambience/flies.wav
sound/ambience/rascheln.wav
sound/ambience/rua3.wav
sound/ambience/sp_thunder.wav
sound/ambience/sub_trainpass.wav
sprites/flame.spr
sprites/glow01.spr
sprites/rk_yellowflare.spr
sprites/xspark4.spr
