decals.wad
gfx/env/saharabk.tga
gfx/env/saharadn.tga
gfx/env/saharaft.tga
gfx/env/saharalf.tga
gfx/env/saharart.tga
gfx/env/saharaup.tga
maps/de_sahara.bsp
sound/ambience/computalk1.wav
sound/ambience/steamjet1.wav
sound/ambience/truck2.wav
sound/ambience/wind2.wav
sound/ambience/wren1.wav
sound/blast/sultan.wav
sound/blast/talvin1.wav
sound/blast/talvin2.wav
sprites/ballsmoke.spr
sprites/glow04.spr
sprites/stmbal1.spr
sprites/xsmoke1.spr
