as_riverside.wad
as_sanchez.wad
cs_assault2k.wad
cs_bdog.wad
cs_cbble.wad
cs_house.wad
cs_lazy.wad
ctx_sig.wad
de_seaside.wad
decals.wad
es_frantic.wad
gfx/env/bluebk.tga
gfx/env/bluedn.tga
gfx/env/blueft.tga
gfx/env/bluelf.tga
gfx/env/bluert.tga
gfx/env/blueup.tga
halflife.wad
hi_sheep.wad
itsitaly.wad
jos.wad
lazy.wad
maps/de_seaside2k.bsp
mattc2.wad
miscstuff.wad
pa_fact.wad
sound/ambience/Birds4.wav
sound/ambience/Birds9.wav
sound/ambience/waves.wav
sprites/glow01.spr
tfc.wad
tfc2.wad
utrain.wad
