gfx/env/greenbk.tga
gfx/env/greendn.tga
gfx/env/greenft.tga
gfx/env/greenlf.tga
gfx/env/greenrt.tga
gfx/env/greenup.tga
maps/de_scheiterhaufen-f.bsp
models/chick.mdl
models/scheiterhaufen2/nackte.mdl
models/western/deadgign.mdl
sound/ambience/birds9.wav
sound/ambience/dog1.wav
sound/ambience/fallscream.wav
sound/ambience/flies.wav
sound/ambience/wololo.wav
sound/misc/killChicken.wav
sprites/fire.spr
sprites/fire2.spr
