gfx/env/tornskybk.tga
gfx/env/tornskydn.tga
gfx/env/tornskyft.tga
gfx/env/tornskylf.tga
gfx/env/tornskyrt.tga
gfx/env/tornskyup.tga
maps/de_torn.bsp
sound/ambience/burning1.wav
sound/ambience/copter.wav
sound/ambience/cricket.wav
sound/ambience/drips.wav
sound/ambience/jetflyby1.wav
sound/de_torn/tk_steam.wav
sound/de_torn/tk_windStreet.wav
sound/de_torn/torn_AK-47.wav
sound/de_torn/torn_Bomb1.wav
sound/de_torn/torn_Bomb2.wav
sound/de_torn/torn_MGun1.wav
sound/de_torn/torn_Templewind.wav
sound/de_torn/torn_ambience.wav
sound/de_torn/torn_thndrstrike.wav
sound/de_torn/torn_water1.wav
sound/de_torn/torn_water2.wav
sprites/glow04.spr
sprites/xffloor.spr
sprites/xsmoke1.spr
sprites/xssmke1.spr
torntextures.wad
