gfx/env/dustbk.tga
gfx/env/dustdn.tga
gfx/env/dustft.tga
gfx/env/dustlf.tga
gfx/env/dustrt.tga
gfx/env/dustup.tga
maps/de_tuscan32.bsp
models/de_tuscan/tuscan_grass1a.mdl
models/de_tuscan/tuscan_palmtree1.mdl
models/de_tuscan/tuscan_shade1a.mdl
models/de_tuscan/tuscan_shade2a.mdl
models/de_tuscan/tuscan_shade3a.mdl
sprites/yelflare1.spr
