cs_havana.wad
decals.wad
gfx/env/plakabk.tga
gfx/env/plakadn.tga
gfx/env/plakaft.tga
gfx/env/plakalf.tga
gfx/env/plakart.tga
gfx/env/plakaup.tga
maps/de_toscana.bsp
models/3dm_statue.mdl
models/bicycle_dead.mdl
models/de_plaka/plaka_boat1.mdl
models/de_plaka/plaka_fernofdoom.mdl
models/de_plaka/plaka_furniture1.mdl
models/de_plaka/plaka_lilpalm.mdl
models/de_plaka/plaka_seagull2.mdl
models/de_plaka/plaka_shrubberyyy.mdl
models/de_plaka/plaka_tree2.mdl
models/trash.mdl
models/truck_large-brown.mdl
sound/ambience/fortran_suburbs_loop.wav
sound/de_plaka/birds.wav
sound/de_plaka/seagulls.wav
sound/de_plaka/waves.wav
torntextures.wad
