gfx/env/spacebk.tga
gfx/env/spacedn.tga
gfx/env/spaceft.tga
gfx/env/spacelf.tga
gfx/env/spacert.tga
gfx/env/spaceup.tga
maps/de_tmtydj2.bsp
sound/uhhh/barbie2.wav
sound/uhhh/bubbles.wav
sound/uhhh/bustconcrete1.wav
sound/uhhh/coco.wav
sound/uhhh/desert2.wav
sound/uhhh/outofspace.wav
sound/uhhh/prisoner.wav
sound/uhhh/silence.wav
sound/uhhh/ufohum.wav
sound/uhhh/vlasov3.wav
sound/uhhh/windy.wav
sprites/uhhh/aliendance.spr
sprites/uhhh/aliendance2.spr
sprites/uhhh/ballsmoke.spr
sprites/uhhh/flare3.spr
uhhh.wad
