cs_bdog.wad
decals.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
maps/de_train.bsp
sound/ambience/boomer.wav
sound/ambience/dog6.wav
sound/ambience/dog7.wav
sound/ambience/flies.wav
sound/ambience/jetflyby1.wav
sound/ambience/tankidle1.wav
sound/ambience/wren1.wav
sprites/flare1.spr
