decals.wad
gfx/env/city1bk.tga
gfx/env/city1dn.tga
gfx/env/city1ft.tga
gfx/env/city1lf.tga
gfx/env/city1rt.tga
gfx/env/city1up.tga
halflife.wad
maps/de_tpoint2k4.bsp
models/pi_tree1.mdl
models/pi_tree2.mdl
models/props/books2.mdl
models/props/car_lada.mdl
models/props/car_lada_window.mdl
models/props/chair_office.mdl
models/props/couch_leather.mdl
models/props/pot.mdl
models/props/tree_pine.mdl
models/tpoint2k4/couch_black.mdl
models/tpoint2k4/deckenluefter.mdl
sound/ambience/brush_movement1.wav
tpoint2k4.wad
