gfx/env/karnakbk.tga
gfx/env/karnakdn.tga
gfx/env/karnakft.tga
gfx/env/karnaklf.tga
gfx/env/karnakrt.tga
gfx/env/karnakup.tga
maps/de_templecats_2009.bsp
models/mdltemple/anubis.mdl
models/mdltemple/bag_food.mdl
models/mdltemple/barrel.mdl
models/mdltemple/buzzer_teatp_kust.mdl
models/mdltemple/de_anubis_head.mdl
models/mdltemple/egypt_dog1.mdl
models/mdltemple/fern4.mdl
models/mdltemple/gins_vase_g.mdl
models/mdltemple/gins_vase_r.mdl
models/mdltemple/gins_vase_y.mdl
models/mdltemple/ginsengavenger_palm240_256.mdl
models/mdltemple/halla_grass1c.mdl
models/mdltemple/zyn_kingtut.mdl
sound/ambience/soundtemple/drips.wav
sound/ambience/soundtemple/flies.wav
sound/ambience/soundtemple/forestcreek.wav
sound/ambience/soundtemple/karnak2.wav
sound/ambience/soundtemple/sp_woodpecker.wav
