arena_we.wad
czcs_italy.wad
czcs_miami.wad
czde_dust.wad
czde_dust_hl2.wad
czde_stadium_pi.wad
de_powerplant07_btm.wad
gfx/env/tornskybk.tga
gfx/env/tornskydn.tga
gfx/env/tornskyft.tga
gfx/env/tornskylf.tga
gfx/env/tornskyrt.tga
gfx/env/tornskyup.tga
halflife.wad
maps/de_target_arena_b4.bsp
models/target/car_lada.mdl
models/target/jeep-russian.mdl
models/target/van.mdl
models/target/xen_tree3.mdl
sound//ambience/fastline/fastline_station3.wav
sound/target/birds.wav
sound/target/buzz.wav
sound/target/target_city.wav
target_logos.wad
tdk_wad_part1.wad
tdk_wad_part10.wad
tpoint2k4.wad
