gfx/env/DrkGbk.tga
gfx/env/DrkGdn.tga
gfx/env/DrkGft.tga
gfx/env/DrkGlf.tga
gfx/env/DrkGrt.tga
gfx/env/DrkGup.tga
maps/de_upd_aztec.bsp
models/fern.mdl
models/pred_plant.mdl
models/props/barrel_brown.mdl
models/props/barrel_metal.mdl
models/props/lamp_portable_standup.mdl
sound/ambience/rain.wav
sound/de_upd_aztec/metal_bullet.wav
sound/de_upd_aztec/power_transformer.wav
sound/de_upd_aztec/thunder1.wav
sound/de_upd_aztec/thunder2.wav
sound/de_upd_aztec/thunder3.wav
sound/de_upd_aztec/thunder4.wav
sound/de_upd_aztec/thunder5.wav
sound/de_upd_aztec/thunder6.wav
sound/de_upd_aztec/tunnel_wind_loop.wav
sprites/de_upd_aztec/splash.spr
sprites/glow02.spr
