gfx/env/ndfnwbk.tga
gfx/env/ndfnwdn.tga
gfx/env/ndfnwft.tga
gfx/env/ndfnwlf.tga
gfx/env/ndfnwrt.tga
gfx/env/ndfnwup.tga
maps/de_via.bsp
models/NDF_NW/NDF_bush2.mdl
models/NDF_NW/NDF_osdrv.mdl
models/NDF_NW/NDF_sdrvo.mdl
models/NDF_NW/deblo1.mdl
models/NDF_NW/ndf_bjpd.mdl
models/NDF_NW/ndf_bjpd2.mdl
models/NDF_NW/ndf_bure.mdl
models/NDF_NW/ndf_bure1.mdl
models/NDF_NW/ndf_bzls.mdl
models/NDF_NW/ndf_bzlsv.mdl
models/NDF_NW/ndf_cRdrv.mdl
models/NDF_NW/ndf_dgbush.mdl
models/NDF_NW/ndf_guS.mdl
models/NDF_NW/ndf_jela.mdl
models/NDF_NW/ndf_jelaK.mdl
models/NDF_NW/ndf_jelan.mdl
models/NDF_NW/ndf_jelan2.mdl
models/NDF_NW/ndf_jelandu.mdl
models/NDF_NW/ndf_jelav.mdl
models/NDF_NW/ndf_pine.mdl
models/NDF_NW/ndf_pineK.mdl
models/NDF_NW/ndf_pinek.mdl
models/NDF_NW/ndf_pinen.mdl
models/NDF_NW/ndf_zdrvo.mdl
models/player/leet/leet.mdl
sound/NDF_NW/NDF_Ambient.wav
sound/NDF_NW/NDF_Thambience.wav
sound/NDF_NW/NDF_talas.wav
sound/NDF_NW/NDF_unkisa.wav
sound/NDF_NW/crickets1.wav
sprites/NDF_NW/NDF_flerka1.spr
sprites/NDF_NW/NDF_woda.spr
sprites/NDF_NW/NDF_woda0.spr
sprites/ndf_nw/ndf_gl.spr
sprites/ndf_nw/ndf_kruglow.spr
