de_vertigo.wad
decals.wad
gfx/env/tsccity_bk.tga
gfx/env/tsccity_dn.tga
gfx/env/tsccity_ft.tga
gfx/env/tsccity_lf.tga
gfx/env/tsccity_rt.tga
gfx/env/tsccity_up.tga
halflife.wad
maps/de_vertigo.bsp
sound/ambience/fallscream.wav
sound/ambience/wind2.wav
sprites/flare2.spr
