de_volare.wad
decals.wad
gfx/env/volarebk.tga
gfx/env/volaredn.tga
gfx/env/volareft.tga
gfx/env/volarelf.tga
gfx/env/volarert.tga
gfx/env/volareup.tga
halflife.wad
maps/de_volare.bsp
sound/ambience/biggun3.wav
sound/ambience/rocket_groan1.wav
sound/ambience/rocket_groan3.wav
sound/barney/badfeeling.wav
sound/debris/metal5.wav
sound/hassault/hw_spindown.wav
sound/hgrunt/c2a5_hg_abandon.wav
sound/plats/platstop1.wav
sound/volare/vol-airborne.wav
sound/volare/vol-birds.wav
sound/volare/vol-bridgecrush.wav
sound/volare/vol-cavewind.wav
sound/volare/vol-crickets.wav
sound/volare/vol-explode.wav
sound/volare/vol-fallb.wav
sound/volare/vol-fallbf.wav
sound/volare/vol-falls.wav
sound/volare/vol-fallscream.wav
sound/volare/vol-gear.wav
sound/volare/vol-plane.wav
sound/volare/vol-riverf.wav
sound/volare/vol-truck.wav
sound/volare/vol-volare.wav
sound/volare/vol-wind.wav
sprites/cexplo.spr
sprites/eexplo.spr
sprites/glow01.spr
sprites/volare/volare001.SPR
sprites/wall_puff3.spr
sprites/wall_puff4.spr
