gfx/env/costabravabk.tga
gfx/env/costabravadn.tga
gfx/env/costabravaft.tga
gfx/env/costabravalf.tga
gfx/env/costabravart.tga
gfx/env/costabravaup.tga
maps/de_villazamis_cz.bsp
models/catalane/gins_pool_ladder.mdl
models/villa/3dm_beach.mdl
models/villa/3dm_tafel.mdl
models/villa/couch_leather.mdl
models/villa/cs_paris_seat.mdl
models/villa/fastcar.mdl
models/villa/forge_fern1.mdl
models/villa/lamborghini.mdl
models/villa/lettreacalou.mdl
models/villa/lettrebcalou.mdl
models/villa/pastis2.mdl
models/villa/planta.mdl
models/villa/s_bench.mdl
models/villa/shower.mdl
models/villa/sink_small.mdl
models/villa/table_cafe.mdl
models/villa/toilette.mdl
models/villa/zamisparasol.mdl
sound/3dm_bik_plons.wav
sound/cigales.wav
