de_vecindad.wad
decals.wad
gfx/env/trainyardbk.tga
gfx/env/trainyarddn.tga
gfx/env/trainyardft.tga
gfx/env/trainyardlf.tga
gfx/env/trainyardrt.tga
gfx/env/trainyardup.tga
halflife.wad
itsitaly.wad
maps/de_Vecindad.bsp
models/mediumplant.mdl
sound/ambience/waterrun.wav
sound/ambience/wind1.wav
