cs_bdog.wad
cs_office.wad
de_worldconflict.wad
decals.wad
gfx/env/snowbk.tga
gfx/env/snowdn.tga
gfx/env/snowft.tga
gfx/env/snowlf.tga
gfx/env/snowrt.tga
gfx/env/snowup.tga
halflife.wad
jos.wad
maps/de_worldconflict.bsp
sound/ambience/copter.wav
sound/ambience/lv_neon.wav
sound/ambience/wind1.wav
sound/ambience/wind2.wav
sprites/glow01.spr
