gfx/env/dusty_morningbk.tga
gfx/env/dusty_morningdn.tga
gfx/env/dusty_morningft.tga
gfx/env/dusty_morninglf.tga
gfx/env/dusty_morningrt.tga
gfx/env/dusty_morningup.tga
maps/de_wilau.bsp
models/rac/ae_smallbush.mdl
models/rac/bush16.mdl
models/rac/chick.mdl
models/rac/cow.mdl
models/rac/desk_office-mahg.mdl
models/rac/dog.mdl
models/rac/flo_grass.mdl
models/rac/garrafas.mdl
models/rac/hessi_pony01.mdl
models/rac/hessi_pony02.mdl
models/rac/pi_treec.mdl
models/rac/piano.mdl
models/rac/russka_cz_tree1.mdl
models/rac/tree5.mdl
models/rac/tub2.mdl
models/rac/watertower2.mdl
models/rac/xen_plant1.mdl
models/villa/lettreacalou.mdl
models/villa/lettrebcalou.mdl
models/villa/pastis2.mdl
sound/rac/aleluia.wav
sound/rac/ecstasyofgold.wav
sprites/glow01.spr
