chateau.wad
cs_havana.wad
de_storm.wad
de_vertigo.wad
gfx/env/2desertbk.tga
gfx/env/2desertdn.tga
gfx/env/2desertft.tga
gfx/env/2desertlf.tga
gfx/env/2desertrt.tga
gfx/env/2desertup.tga
halflife.wad
itsitaly.wad
maps/de_westwood3.bsp
models/pred_plant.mdl
sound/Ambience/cricket.wav
sound/Ambience/flies.wav
sound/ambience/guit1.wav
sprites/flare1.spr
