cdz.wad
cs_espana.wad
gfx/env/badlandsbk.tga
gfx/env/badlandsdn.tga
gfx/env/badlandsft.tga
gfx/env/badlandslf.tga
gfx/env/badlandsrt.tga
gfx/env/badlandsup.tga
halflife.wad
itsitaly.wad
maps/de_wayofguns.bsp
