cs_cbble.wad
cs_office.wad
de_piranesi.wad
gfx/env/morningdewbk.tga
gfx/env/morningdewdn.tga
gfx/env/morningdewft.tga
gfx/env/morningdewlf.tga
gfx/env/morningdewrt.tga
gfx/env/morningdewup.tga
halflife.wad
maps/fy_buzzkill2005.bsp
torntextures.wad
