cs_bdog.wad
de_piranesi.wad
gfx/env/tsccity_bk.tga
gfx/env/tsccity_dn.tga
gfx/env/tsccity_ft.tga
gfx/env/tsccity_lf.tga
gfx/env/tsccity_rt.tga
gfx/env/tsccity_up.tga
halflife.wad
maps/he_tennis.bsp
models/player/arctic/arctic.mdl
models/player/guerilla/guerilla.mdl
models/player/leet/leet.mdl
models/player/terror/terror.mdl
