chateau.wad
gfx/env/snowlake_bk.tga
gfx/env/snowlake_dn.tga
gfx/env/snowlake_ft.tga
gfx/env/snowlake_lf.tga
gfx/env/snowlake_rt.tga
gfx/env/snowlake_up.tga
halflife.wad
itsitaly.wad
maps/xmas_nipperhouse.bsp
sound/SNL_xmas.wav
